/* autogenerated by Processing revision 1313 on 2026-05-19 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import ddf.minim.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Chess_vs_Shogi extends PApplet {

/*
チェスVS将棋
AIは作っていないので、一緒に遊ぶ友達を用意していください
 */
//ライブラリ

float consoleSize;//画面右の領域の横幅
float stage_x, stage_y;//盤面の座標
float stage_size;//盤面のサイズ
float[][] s_size;
float box_size;//盤のマス目の大きさ
int choose_x, choose_y;//選択している駒
int upHave[] = new int[7];//持ち駒
int downHave[] = new int[7];
int upHaveChess[] = new int[5];//チェスの持ち駒
int downHaveChess[] = new int[5];
boolean choose;//駒の選択をしているか判別する変数
boolean haveChoose;//持ち駒の選択をしているか判別する変数
boolean haveChessChoose;
boolean backPlay;//ゲーム画面に戻るための変数
int FPS;//フレームレート
boolean canPut;//駒が動かせるか判断する変数
boolean canHavePut;//持ち駒が置けるか判断する処理
boolean canHaveChessPut;//チェスの持ち駒が置けるか判断する処理
int turn_num = 0;//ターンの番号が入る処理(1で下側、2で上側)
int mouseHave;
int mouseHaveChess;
int mouseHaveOption;//クリックした瞬間の持ち駒の種類が入る
int have_num;
float haveX=0, haveY=0; //持ち駒選択した瞬間の座標
int pop;//ポップアップを出すか判断する変数
boolean[] castlingPieces = new boolean[3];//キャスリングができるかどうかを判定するときに使う変数
boolean[] syogiCastlingPieces = new boolean[3];//将棋側のキャスリングができるかどうか判定する変数
boolean castlingQueen, castlingKing;//クイーンサイドキャスリングかキングサイドキャスリングができるか判断する変数
boolean syogiCastlingLeft, syogiCastlingRight;//将棋のレフトキャスリングかライトキャスリングができるか判断する変数
boolean upCastling;//キャスリングを1回だけにする変数
boolean downCastling;//将棋のキャスリングを1回だけにする変数
boolean canCastling;//
boolean canSyogiCastling;//
boolean castMode;//キャスリングモードか判断する変数
boolean syogiCastMode;
boolean queenSide, kingSide;
boolean leftSide, rightSide;
boolean resign;//降参するボタンを押したかどうかの判定に使われる
boolean fixTesu;//ゲーム終了時の手数の表示を直すために使用する変数
int gear;//複数タブの表現を行う
int win;//どちらが勝ったかを判定する変数(1で下2で上)
boolean[] rules = new boolean[6];
int[] options = new int[6];//カスタムモードの設定に使う
int tesu;//手数を記録、表示する
boolean canBackCheck;
public void setup() {//いろんな変数の初期化を行う
  /* size commented out by preprocessor */;//画面サイズの設定
  PFont font = createFont("Meiryo", 30);//ここで日本語化を行っている
  textFont(font);
  consoleSize = 200;//画面右の領域のサイズの設定
  stage_size = 600;//盤面の大きさの設定
  FPS = 60;//フレームレートの設定(タイマーはこの値を利用している)
  frameRate(FPS);
  initView();//盤面の初期化
  initImage();//画像の初期化
  initMove();//駒の動き関係の初期化
  initHave();//持ち駒関係の初期化
  initCastling();//キャスリング関係の初期化
  initSound();//音の初期化
  initTimer();//タイマーの初期化
  initElse();//その他の初期化
  initPopUp();//駒の成りなどで使うポップアップの初期化
}

public void draw() {
  switch(gear) {//[break;]忘れに要注意
  case 0:
    menu();//メニュー画面
    break;

  case 1:
    startTimer();//タイマーをスタートする関数
    play();//ゲームプレイ画面
    break;

  case 2://プレイ画面
    originalSet();//オリジナルモードでのプレイ
    gear = 9;
    break;

  case 3:
    balanceSet();//バランスモードでのプレイ
    gear = 9;
    break;

  case 4:
    customSet();//カスタムモードでのプレイ
    gear = 9;
    break;

  case 5:
    gameEnd();//ゲームを終える画面
    break;

  case 6:
    option();//設定画面
    break;

  case 7:
    explain();//特殊ルールを説明するモード
    break;

  case 8:
    breakTime();//休憩モード
    break;

  case 9:
    confirm();//
    break;
  }
  if (time_han) {
    time++;
  }
}

public void move(int x, int y) {//駒を選択したときに通る処理
  int move;
  move = stage_piece_num[y][x];

  choose = true;//選択モード
  choose_x = x;//選択した駒の位置
  choose_y = y;
}

public boolean turnCheck(int y, int x, int turn_num ) {//指定した座標の駒の陣営と現在のターンとあっているか確認する関数
  boolean check = false;
  int[] soeji = bunnkai(stage_piece_num[y][x]);
  if (soeji[0] == turn_num) {
    check = true;
  }
  return check;
}
/*ボタン関係の処理が入ります(クラス化すればよかった…)*/
public void originalButton() {//オリジナルモードで始めるためのボタン
  int[] textColor = {0, 0, 0};//ボタンの文字の色
  int[] rectColor = {235, 246, 247};//ボタンの四角の色
  int t_s = 30;//文字サイズ
  textSize(t_s);
  String moji = "オリジナルモード";
  textRect(width/2 - (moji.length())/2*t_s, height/2, moji, t_s, rectColor, textColor);
  float x = (width/2 - (moji.length())/2*t_s) + 5;
  float y =  height/2 + 5;
  float x_s = moji.length()*t_s + 10;
  float y_s = t_s + 10;
  originalMode = false;
  if ( mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    originalMode = true;
  }
}

public void balanceButton() {//バランスモードで始めるためのボタン

  int[] textColor = {0, 0, 0};
  int[] rectColor = {235, 246, 247};
  int t_s = 30;
  textSize(t_s);
  String moji = "バランスモード";
  textRect(width/2 - (moji.length())/2*t_s, height/2 + t_s*2, moji, t_s, rectColor, textColor);//文字を四角付きで表示する関数
  float x = (width/2 - (moji.length())/2*t_s) + 5;
  float y =  height/2 + t_s*2+ 5;
  float x_s = moji.length()*t_s + 10;
  float y_s = t_s + 10;
  balanceMode = false;
  if ( mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    balanceMode = true;
  }
}

public void customButton() {//カスタムモードで始めるためのボタン

  int[] textColor = {0, 0, 0};
  int[] rectColor = {235, 246, 247};
  int t_s = 30;
  textSize(t_s);
  String moji = "カスタムモード";
  textRect(width/2 - (moji.length())/2*t_s, height/2 + t_s*4, moji, t_s, rectColor, textColor);
  float x = (width/2 - (moji.length())/2*t_s) + 5;
  float y =  height/2 + t_s*4+ 5;
  float x_s = moji.length()*t_s + 10;
  float y_s = t_s + 10;
  customMode = false;
  if ( mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    customMode = true;
  }
}

public void optionButton() {//カスタムモードの設定画面に行くためのボタン

  int[] textColor = {0, 0, 0};
  int[] rectColor = {235, 246, 247};
  int t_s = 30;
  textSize(t_s);
  String moji = "設定";
  textRect(width/2 - (moji.length())/2*t_s + 170, height/2 + t_s*4, moji, t_s, rectColor, textColor);
  float x = (width/2 - (moji.length())/2*t_s + 170) + 5;
  float y =  height/2 + t_s*4+ 5;
  float x_s = moji.length()*t_s + 10;
  float y_s = t_s + 10;
  optionMode = false;
  if ( mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    optionMode = true;
  }
}
public void explainButton() {//特殊ルール(チェスの成りと将棋のキャスリング)の説明

  int[] textColor = {0, 0, 0};
  int[] rectColor = {235, 246, 247};
  int t_s = 30;
  textSize(t_s);
  String moji = "特殊ルールの説明";
  textRect(width/2 - (moji.length())/2*t_s, height/2 + t_s*6, moji, t_s, rectColor, textColor);
  float x = (width/2 - (moji.length())/2*t_s) + 5;
  float y =  height/2 + t_s*6+ 5;
  float x_s = moji.length()*t_s + 10;
  float y_s = t_s + 10;
  explainMode = false;
  if ( mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    explainMode = true;
  }
}
public boolean breakTimeButton(boolean can) {//休憩するためのボタン
  int[] textColor = {0, 0, 0};
  int[] rectColor = {235, 246, 247};
  int t_s = 30;
  textSize(t_s);
  String moji = "休憩をとる";
  boolean canBreakTime;
  canBreakTime = false;
  textRect(width-consoleSize + 20, 600, moji, t_s, rectColor, textColor);
  float x = width-consoleSize + 20 + 5;
  float y = 600 + 5;
  float x_s = moji.length() * t_s + 10;
  float y_s = t_s + 10;
  if (mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s && can) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    canBreakTime = true;
  }


  return canBreakTime;
}
public void playButton() {
  backPlay = false;
  String moji = "ゲームに戻る";
  int t_s = 30;
  textSize(t_s);
  int[] rectColor = {240, 240, 240};
  int[] textColor = {0, 0, 0};
  textRect(0, 0, moji, t_s, rectColor, textColor);
  int x_s, y_s;
  x_s = moji.length() * t_s + 10;
  y_s = t_s + 10;
  if (mouseX >= 5 && mouseX <= 5 + x_s && mouseY >= 5 && mouseY <= 5 + y_s) {
    backPlay = true;
    fill(0, 0, 0, 80);
    rect(5, 5, x_s, y_s);
  }
}
public void resignButton(boolean can) {//投了・リザインボタン
  int[] textColor = {0, 0, 0};
  int[] rectColor = {235, 246, 247};
  int t_s = 30;
  textSize(t_s);
  String moji;
  if (turn_num == 1) {
    moji = "投了";
  } else {
    moji = "リザイン";
  }

  resign = false;
  textRect(width-consoleSize + 20, 500, moji, t_s, rectColor, textColor);
  float x = width-consoleSize + 20 + 5;
  float y = 500 + 5;
  float x_s = moji.length() * t_s + 10;
  float y_s = t_s + 10;
  if (mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s && can) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    resign = true;
  }
}
public void viewOptionButtons() {//設定画面のボタン
  option1 = false;
  option2 = false;
  option3 = false;
  original_option = false;
  balance_option = false;

  float x, y, x_size, y_size;
  int[] rectColor = new int[3];
  int[] textColor = new int[3];
  String[] mojis = new String[4];
  int t_s = 20;
  textSize(t_s);
  x = width /2 + 80;
  y = 250;
  x_size = 100;
  y_size = 60;
  fill(235, 246, 247, 255);
  rect(x, y, x_size, y_size);
  fill(0, 0, 0);
  text("チェスのみ", x, y + (y_size+t_s)/2);//基準
  rectColor[0] = 235;
  rectColor[1] = 246;
  rectColor[2] = 247;
  textColor[0] = 0;
  textColor[1] = 0;
  textColor[2] = 0;
  mojis[0] = "両方無し";
  mojis[1] = "両方あり";
  mojis[2] = "将棋のみ";
  mojis[3] = "チェスのみ";
  /*効率が悪いコードになるがif文のなかが違うのでしょうがない←配列化していないのが悪い*/
  for (int n = 0; n < 4; n++) {//option1の内容
    float m_x;//yはそのままだったので必要無し
    m_x = x + (x_size + 10)*n;
    fill(235, 246, 247);
    rect(m_x, y, x_size, y_size);
    fill(0, 0, 0);
    text(mojis[n], x + (x_size + 10)*n, y + (y_size+t_s)/2);
    if (option1_num != n) {
      fill(0, 0, 0, 160);
      rect(x + (x_size + 10)*n, y, x_size, y_size);
    }
    if (mouseX >= m_x && mouseX <= m_x + x_size && mouseY >= y && mouseY <= y + y_size) {
      option1 = true;
      change_option1 = n;
    }
  }
  y += 80;
  for (int n = 0; n < 4; n++) {//option2の内容
    float m_x;//yはそのままだったので必要無し
    m_x = x + (x_size + 10)*n;
    fill(235, 246, 247);
    rect(m_x, y, x_size, y_size);
    fill(0, 0, 0);
    text(mojis[n], x + (x_size + 10)*n, y + (y_size+t_s)/2);
    if (option2_num != n) {
      fill(0, 0, 0, 160);
      rect(x + (x_size + 10)*n, y, x_size, y_size);
    }
    if (mouseX >= m_x && mouseX <= m_x + x_size && mouseY >= y && mouseY <= y + y_size) {
      option2 = true;
      change_option2 = n;
    }
  }
  y += 80;
  for (int n = 0; n < 4; n++) {//option3の内容
    float m_x;//yはそのままだったので必要無し
    m_x = x + (x_size + 10)*n;
    fill(235, 246, 247);
    rect(m_x, y, x_size, y_size);
    fill(0, 0, 0);
    text(mojis[n], x + (x_size + 10)*n, y + (y_size+t_s)/2);
    if (option3_num != n) {
      fill(0, 0, 0, 160);
      rect(x + (x_size + 10)*n, y, x_size, y_size);
    }
    if (mouseX >= m_x && mouseX <= m_x + x_size && mouseY >= y && mouseY <= y + y_size) {
      option3 = true;
      change_option3 = n;
    }
  }

  /*この下は固定セットのボタン*/
  String moji;
  float b_x, b_y, b_x_s, b_y_s;
  t_s = 30;
  textSize(t_s);
  moji = "オリジナルセット";
  x = width/2 - 300;
  y = height - 100;
  textRect(x, y, moji, t_s, rectColor, textColor);
  b_x = x + 5;
  b_y = y + 5;
  b_x_s = moji.length() * t_s + 10;
  b_y_s = t_s + 10;
  if (mouseX >= b_x && mouseX <= b_x + b_x_s && mouseY >= b_y && mouseY <= b_y + b_y_s) {
    original_option = true;
    fill(255, 255, 0, 80);
    rect(b_x, b_y, b_x_s, b_y_s);
  }

  x += 300;
  moji = "バランスセット";
  textRect(x, y, moji, t_s, rectColor, textColor);
  b_x = x + 5;
  b_y = y + 5;
  b_x_s = moji.length() * t_s + 10;
  b_y_s = t_s + 10;
  if (mouseX >= b_x && mouseX <= b_x + b_x_s && mouseY >= b_y && mouseY <= b_y + b_y_s) {
    balance_option = true;
    fill(255, 255, 0, 80);
    rect(b_x, b_y, b_x_s, b_y_s);
  }
}

public void backButton() {//メニュー画面に戻るためのボタン
  back = false;
  int t_s = 40;
  int[] rectColor = {255, 255, 0};
  int[] textColor = {0, 0, 0};
  textSize(t_s);
  textRect(0, 0, "戻る", t_s, rectColor, textColor);
  int x, y, x_s, y_s;
  x = 5;
  y = 5;
  x_s = t_s*2 + 10;
  y_s = t_s + 10;
  if (mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    back = true;
  }
}
public void startButton() {//ゲームを始めるボタン
  start = false;
  int t_s = 40;
  int[] rectColor = {255, 255, 0};
  int[] textColor = {0, 0, 0};
  String moji;
  moji = "ゲームを始める";
  textSize(t_s);
  textRect(width/2 - moji.length()/2 * t_s, height-120, moji, t_s, rectColor, textColor);
  int x, y, x_s, y_s;
  x = width/2 - moji.length()/2 * t_s + 5;
  y = height-120 + 5;
  x_s = t_s*moji.length() + 10;
  y_s = t_s + 10;
  if (mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    start = true;
  }
}

public void backPieceButton(boolean can) {
  int[] textColor = {0, 0, 0};
  int[] rectColor = {235, 246, 247};
  int t_s = 30;
  textSize(t_s);
  String moji;
  moji = "一手戻る";

  canBackCheck = false;
  textRect(width-consoleSize + 20, 700, moji, t_s, rectColor, textColor);
  float x = width-consoleSize + 20 + 5;
  float y = 700 + 5;
  float x_s = moji.length() * t_s + 10;
  float y_s = t_s + 10;
  if (mouseX >= x && mouseX <= x + x_s && mouseY >= y && mouseY <= y + y_s && can) {
    fill(0, 0, 255, 80);
    rect(x, y, x_s, y_s);
    canBackCheck = true;
  }
}
public int[] bunnkai(int ex_num) {//3または4桁の数字を3つに分解する,例1234→1,2,34の3つに分ける
  int[]data;
  data = new int[3];
  int num1, num2, num3;
  if (ex_num < 1000) {//桁数の確認
    num3 = ex_num%10;
    num2 = ((ex_num%100) - num3) / 10;
    num1 = (ex_num - (num2+num3)) / 100;
  } else {
    num3 = ex_num%100;
    num2 = ((ex_num%1000)-num3)/100;
    num1 = (ex_num - (num3+num2))/1000;
  }
  data[0] = num1;//上側陣営か下側陣営か
  data[1] = num2;//将棋かチェスか
  data[2] = num3;//駒の種類

  return data;
}
/*少し特殊なルールのキャスリングに関係する処理をまとめる*/
boolean cast;
float x_p, y_p, x_s, y_s;
public void initCastling() {//キャスリングに使用する変数の初期化
  downCastling = true;//下側のキャスリングを1回にするための変数
  leftSide = false;//下側陣営の左のキャスリングができるか判断する変数
  rightSide = false;//下側陣営の右のキャスリングができるか判断する変数
  cast = false;
  castlingQueen = true;
  castlingKing = true;
  upCastling = true;
  canCastling = false;//上側のキャスリングができるか判断する変数
  canSyogiCastling = false;//上側のキャスリングができるか判断する変数
  castMode = false;//キャスリングモードか判断する変数
  syogiCastMode = false;//下側のキャスリングモードか判断する変数
  for (int n = 0; n < syogiCastlingPieces.length; n++) {//キャスリングに使われる駒が動いたり取られたりしたときにfalseになる
    syogiCastlingPieces[n] = true;
  }
  for (int n = 0; n < castlingPieces.length; n++) {//キャスリングに使われる駒が動いたり取られたりしたときにfalseになる
    castlingPieces[n] = true;
  }
}
public void castling() {//上側がキャスリングできるときにキャスリングボタンを表示する関数
  int[] textColor = {0, 0, 0};
  int[] rectColor = {235, 246, 247};
  int t_s;
  t_s = 20;
  textSize(t_s);
  float x, y;
  x = width-consoleSize + 20;
  y = 400;
  textRect(x, y, "キャスリング", t_s, rectColor, textColor);
  x_p = x+5;
  y_p = y+5;
  x_s = 6 * t_s + 10;
  y_s = t_s + 10;
  canCastling = false;
  if (mouseX >= x_p && mouseX <= x_p+x_s && mouseY >= y_p && mouseY <= y_p + y_s && !(castMode) && !(choose) && !(haveChoose)) {
    fill(0, 0, 255, 80);
    rect(x_p, y_p, x_s, y_s);
    canCastling = true;
  }
  if (castMode) {
    fill(0, 255, 0, 80);
    rect(x_p, y_p, x_s, y_s);
  }
}
public void syogiCastling() {//下側がキャスリングできるときにボタンを表示する関数
  int[] textColor = {0, 0, 0};
  int[] rectColor = {235, 246, 247};
  int t_s;
  t_s = 20;
  textSize(t_s);
  float x, y;
  x = width-consoleSize + 20;
  y = height/2;
  textRect(x, y, "キャスリング", t_s, rectColor, textColor);
  x_p = x+5;
  y_p = y+5;
  x_s = 6 * t_s + 10;
  y_s = t_s + 10;
  canSyogiCastling = false;
  if (mouseX >= x_p && mouseX <= x_p+x_s && mouseY >= y_p && mouseY <= y_p + y_s && !(castMode) && !(choose) && !(haveChoose) && !(syogiCastMode)) {
    fill(0, 0, 255, 80);
    rect(x_p, y_p, x_s, y_s);
    canSyogiCastling = true;
  }
  if (syogiCastMode) {
    fill(0, 255, 0, 80);
    rect(x_p, y_p, x_s, y_s);
  }
}

public boolean castlingCheck(int turn) {//ターンごとにキャスリグができるか判断する関数
  boolean check;
  check = false;
  if (turn == 2) {
    if (castlingPieces[0]) {
      castlingQueen = false;
      boolean can = stage_piece_num[0][1]==0 && stage_piece_num[0][2] == 0  && stage_piece_num[0][3] == 0;
      if (castlingPieces[1] && can ) {//クイーンサイド
        castlingQueen = true;
        for (int n = 0; n < downCanMove.length; n++) {
          for (int j = 0; j < downCanMove[n].length; j++) {
            for ( int i = 0; i < downCanMove[n][j].length; i++) {
              if (downCanMove[n][j][i][0] == 0 && (downCanMove[n][j][i][1] == 2 || downCanMove[n][j][i][1] == 3|| downCanMove[n][j][i][1] == 4)) {
                //キャスリングができないときにfalseになる
                castlingQueen = false;

                break;
              }
            }
            if (!(castlingQueen)) {
              break;
            }
          }
          if (!(castlingQueen)) {
            break;
          }
        }
      }

      castlingKing = false;
      can =stage_piece_num[0][5] == 0 && stage_piece_num[0][6] == 0;//間に何もないか判定している
      if (castlingPieces[2] && can) {//キングサイド

        castlingKing = true;
        for (int n = 0; n < downCanMove.length; n++) {
          for (int j = 0; j < downCanMove[n].length; j++) {
            for ( int i = 0; i < downCanMove[n][j].length; i++) {
              if (downCanMove[n][j][i][0] == 0 && (downCanMove[n][j][i][1] == 5 || downCanMove[n][j][i][1] == 6|| downCanMove[n][j][i][1] == 4)) {
                //キャスリングができないときにfalseになる
                castlingKing = false;

                break;
              }
            }
            if (!(castlingKing)) {
              break;
            }
          }
          if (!(castlingKing)) {
            break;
          }
        }
      }

      if (castlingQueen || castlingKing) {
        check = true;
      }
    }
  }
  if (turn_num == 1) {//下側のターンの場合
    if (syogiCastlingPieces[0]) {
      syogiCastlingLeft = false;
      boolean can = stage_piece_num[8][1]==0 && stage_piece_num[8][2] == 0  && stage_piece_num[8][3] == 0;
      if (syogiCastlingPieces[1] && can ) {//レフトサイド
        syogiCastlingLeft = true;
        for (int n = 0; n < upCanMove.length; n++) {
          for (int j = 0; j < upCanMove[n].length; j++) {
            for ( int i = 0; i < upCanMove[n][j].length; i++) {
              if (upCanMove[n][j][i][0] == 8 && (upCanMove[n][j][i][1] == 2 || upCanMove[n][j][i][1] == 3|| upCanMove[n][j][i][1] == 4)) {

                //キャスリングができないときにfalseになる
                syogiCastlingLeft = false;

                break;
              }
            }
            if (!(syogiCastlingLeft)) {
              break;
            }
          }
          if (!(syogiCastlingLeft)) {
            break;
          }
        }
      }

      syogiCastlingRight = false;
      can = stage_piece_num[8][5] == 0 && stage_piece_num[8][6] == 0 && stage_piece_num[8][7] == 0;
      if (syogiCastlingPieces[2] && can) {//キングサイド

        syogiCastlingRight = true;
        for (int n = 0; n < upCanMove.length; n++) {
          for (int j = 0; j < upCanMove[n].length; j++) {
            for ( int i = 0; i < upCanMove[n][j].length; i++) {
              if (upCanMove[n][j][i][0] == 8 && (upCanMove[n][j][i][1] == 5 || upCanMove[n][j][i][1] == 6|| upCanMove[n][j][i][1] == 4)) {
                //キャスリングができないときにfalseになる
                syogiCastlingRight = false;

                break;
              }
            }
            if (!(syogiCastlingRight)) {
              break;
            }
          }
          if (!(syogiCastlingRight)) {
            break;
          }
        }
      }

      if (syogiCastlingLeft || syogiCastlingRight) {
        check = true;
      }
    }
  }
  return check;
}

public void castlingChange( int x) {//駒が動く、取られるなどしてキャスリングができなくなる時実行される関数
  if ( x == 4 && castlingPieces[0]) {//キングだったら

    castlingPieces[0] = false;
  } else if (castlingPieces[1] && x == 0) {//クイーンサイドルークだったら

    castlingPieces[1] = false;
  } else if (castlingPieces[2]) {//キングサイドルークだったら
    castlingPieces[2] = false;
  }
}
public void syogiCastlingChange(int x) {
  if ( x == 4 && syogiCastlingPieces[0]) {//王だったら

    syogiCastlingPieces[0] = false;
  } else if (syogiCastlingPieces[1] && x == 0) {//レフトサイド香車だったら

    syogiCastlingPieces[1] = false;
  } else if (syogiCastlingPieces[2]) {//ライトサイド香車だったら
    syogiCastlingPieces[2] = false;
  }
}

public void castRect() {//キャスリングボタンを押した後にキャスリングができる駒に色を塗る処理
  if (castlingQueen) {//クイーンサイドキャスリングができるとき
    fill(255, 0, 0, 80);
    rect(stage_x, stage_y, box_size, box_size);
    queenSide = false;
    if (mouseX >= stage_x && mouseX<= stage_x + box_size && mouseY >= stage_y && mouseY <= stage_y+box_size) {
      fill(0, 255, 0, 80);
      rect(stage_x, stage_y, box_size, box_size);
      queenSide = true;
    }
  }
  if (castlingKing) {//キングサイドキャスリングができるとき
    fill(255, 0, 0, 80);
    rect(stage_x + box_size*7, stage_y, box_size, box_size);
    kingSide = false;
    if (mouseX >= stage_x + box_size*7 && mouseX<= stage_x + box_size*8 && mouseY >= stage_y && mouseY <= stage_y+box_size) {
      fill(0, 255, 0, 80);
      rect(stage_x + box_size*7, stage_y, box_size, box_size);
      kingSide = true;
    }
  }
}

public void syogiCastRect() {//キャスリングボタンを押した後にキャスリングができる駒に色を塗る処理
  if (syogiCastlingLeft) {//レフトサイドキャスリングができるとき
    fill(255, 0, 0, 80);
    rect(stage_x, stage_y + box_size*8, box_size, box_size);
    leftSide = false;
    if (mouseX >= stage_x && mouseX<= stage_x + box_size && mouseY >= stage_y + box_size*8 && mouseY <= stage_y+box_size*9) {
      fill(0, 255, 0, 80);
      rect(stage_x, stage_y + box_size*8, box_size, box_size);
      leftSide = true;
    }
  }
  if (syogiCastlingRight) {//ライトサイドキャスリングができるとき
    fill(255, 0, 0, 80);
    rect(stage_x + box_size*8, stage_y + box_size*8, box_size, box_size);
    rightSide = false;
    if (mouseX >= stage_x + box_size*8 && mouseX<= stage_x + box_size*9 && mouseY >= stage_y + box_size*8 && mouseY <= stage_y+box_size*9) {
      fill(0, 255, 0, 80);
      rect(stage_x + box_size*8, stage_y + box_size*8, box_size, box_size);
      rightSide = true;
    }
  }
}

public void kingSideCastling() {//キャスリングをする処理
  backSave();//一手戻るために記録をしている
  stage_piece_num[0][4] = 0;
  stage_piece_num[0][7] = 0;
  stage_piece_num[0][6] = 210;
  stage_piece_num[0][5] = 212;
}

public void queenSideCastling() {//キャスリングをする処理
  backSave();//一手戻るために記録をしている
  stage_piece_num[0][4] = 0;
  stage_piece_num[0][0] = 0;
  stage_piece_num[0][2] = 210;
  stage_piece_num[0][3] = 212;
}
public void leftSideCastling() {//キャスリングをする処理
  backSave();//一手戻るために記録をしている
  stage_piece_num[8][4] = 0;
  stage_piece_num[8][0] = 0;
  stage_piece_num[8][2] = 100;
  stage_piece_num[8][3] = 102;
}

public void rightSideCastling() {//キャスリングをする処理
  backSave();//一手戻るために記録をしている
  stage_piece_num[8][4] = 0;
  stage_piece_num[8][8] = 0;
  stage_piece_num[8][6] = 100;
  stage_piece_num[8][5] = 102;
}
/*いろんなところから呼び出される予定の便利な関数を記録する。
 または、他のタブに分類されない関数*/
//行って戻るときに使う変数
int[] upBackHaveSyogi, upBackHaveChess, downBackHaveSyogi, downBackHaveChess;
int[][] back_stage_piece_num;
boolean[] backCastlingChess, backCastlingSyogi;
boolean canBack, backUpCastling, backDownCastling;

public void initElse() {//分類されない変数などの初期化を行う
  resign = false;//降参するかどうかを判断する変数
  fixTesu = true;//結果表示時に手数を直す処理
  gear = 0;//初めにメニュー画面に行くようにする
  choose = false;//初めは何も選択していないので、[false]が入る
  turn_num = PApplet.parseInt(random(1, 3));//ターンはランダムで決める
  pop = 0;
  tesu = 1;//手数の初期化(後から気づいたが読みは"てかず")
  for (int n = 0; n < rules.length; n++) {//ルールの初期化
    rules[n] = false;
  }
  /*カスタムモード設定に関する変数の初期化
   0→両方無し、1→両方あり、2→将棋のみ,3→チェスのみ
   初期設定はオリジナルモードと同じ
   */
  option1_num = 2;//持ち駒
  option2_num = 1;//駒の成り
  option3_num = 3;//キャスリング
  canBack = false;
  back_stage_piece_num = new int[9][9];
  upBackHaveSyogi = new int[7];
  upBackHaveChess = new int[5];
  downBackHaveSyogi = new int[7];
  downBackHaveChess = new int[5];
  backCastlingChess = new boolean[3];
  backCastlingSyogi = new boolean[3];
  canBackCheck = false;
}


public void textRect(float x, float y, String moji, int size, int[] rect_color, int[] text_color) {//文字を長方形の中に入れるボタンを作る目的
  /*引数は左から座標、座標、表示する文字列、文字の大きさ,長方形の色、表示する文字の色*/
  int moji_size;
  x = x+5;
  y = y+5;

  moji_size = moji.length();
  fill(rect_color[0], rect_color[1], rect_color[2]);
  rect(x, y, moji_size*size + 10, size + 10);
  x = x+5;
  fill(text_color[0], text_color[1], text_color[2]);
  text(moji, x, y+size);
}

public void promotion(int[] proPiece, int popCheck) {//この言い方はチェスの言い方だけど将棋の処理も含む
  int[] soeji ;
  int y, x;
  int piece;
  int piece_num;
  soeji = bunnkai(proPiece[0]);
  int soeji1, soeji2, soeji3;
  soeji1 = soeji[0];
  soeji2 = soeji[1];
  soeji3 = soeji[2];
  y = proPiece[1];
  x = proPiece[2];
  if (soeji2 == 1) {//チェスの場合
    switch(popCheck) {
    case 1:
      piece_num = PApplet.parseInt(str(soeji1) + str(15));
      stage_piece_num[y][x] = piece_num;
      break;

    case 2:
      piece_num = PApplet.parseInt(str(soeji1) + str(14));
      stage_piece_num[y][x] = piece_num;
      break;

    case 3:
      piece_num = PApplet.parseInt(str(soeji1) + str(12));
      stage_piece_num[y][x] = piece_num;
      break;

    case 4:
      piece_num = PApplet.parseInt(str(soeji1) + str(13));
      stage_piece_num[y][x] = piece_num;
      break;
    }
  } else {//将棋の場合
    piece = conversion(soeji3);
    piece_num = PApplet.parseInt(str(soeji1)+str(soeji2)+str(piece));
    stage_piece_num[y][x] = piece_num;
  }
}

public int conversion(int ex_option) {
  int option;
  if (ex_option >= 1 && ex_option<= 4) {
    option = ex_option+7;
  } else {
    option = ex_option + 6;
  }
  return option;
}

public void turnChange() {
  if (turn_num == 1) {//ここではターンの入れ替えを行う
    turn_num = 2;
  } else {
    turn_num = 1;
  }
  tesu++;//ターンが変わるのと同時に手数を増やす
}

public boolean checkCheck() {//チェック、王手確認用関数
  boolean kingCheck;
  kingCheck = false;
  int[][][][] canMoves;
  int king;
  int y, x;//キングや王が今現在いる位置の座標が入る
  boolean find;//キングが見つかったらtrueが入る
  if (turn_num == 1) {
    canMoves = upCanMove;
    king = 100;
  } else {
    canMoves = downCanMove;
    king = 210;
  }
  y = 0;
  x = 0;//エラー回避用
  find = false;
  for (int n = 0; n < stage_piece_num.length; n++) {
    for (int j = 0; j < stage_piece_num[n].length; j++) {
      if (stage_piece_num[n][j] == king) {
        y = n;
        x = j;
        find = true;
        break;
      }
    }
    if (find) {
      break;
    }
  }

  for (int n = 0; n < canMoves.length; n++) {
    for (int j = 0; j < canMoves[n].length; j++) {
      for (int i = 0; i < canMoves[n][j].length; i++) {
        if (canMoves[n][j][i][0] == y && canMoves[n][j][i][1] == x) {
          kingCheck = true;
          break;
        }
      }
      if (kingCheck) {
        break;
      }
    }
    if (kingCheck) {
      break;
    }
  }



  return kingCheck;
}
public void backSave() {//一手戻るために駒の情報をセーブする関数
  for (int n = 0; n < upHave.length; n++) {
    upBackHaveSyogi[n] = upHave[n];
    downBackHaveSyogi[n] = downHave[n];
  }
  for (int n = 0; n < upHaveChess.length; n++) {
    upBackHaveChess[n] = upHaveChess[n];
    downBackHaveChess[n] = downHaveChess[n];
  }
  for (int n = 0; n < stage_piece_num.length; n++) {
    for (int j = 0; j < stage_piece_num[n].length; j++) {
      back_stage_piece_num[n][j] = stage_piece_num[n][j];
    }
  }
  for (int n = 0; n < castlingPieces.length; n++) {
    backCastlingChess[n] = castlingPieces[n];
    backCastlingSyogi[n] = syogiCastlingPieces[n];
  }
  backUpCastling = upCastling;
  backDownCastling = downCastling;
  canBack = true;//一手戻れるようにしている
}

public void backPiece() {//実際に一手戻る関数
  for (int n = 0; n < upHave.length; n++) {
    upHave[n] = upBackHaveSyogi[n];
    downHave[n] = downBackHaveSyogi[n];
  }
  for (int n = 0; n < upHaveChess.length; n++) {
    upHaveChess[n] = upBackHaveChess[n];
    downHaveChess[n] = downBackHaveChess[n];
  }
  for (int n = 0; n < stage_piece_num.length; n++) {
    for (int j = 0; j < stage_piece_num[n].length; j++) {
      stage_piece_num[n][j] = back_stage_piece_num[n][j];
    }
  }
  for (int n = 0; n < castlingPieces.length; n++) {
    castlingPieces[n] = backCastlingChess[n];
    syogiCastlingPieces[n] = backCastlingSyogi[n];
  }
  upCastling = backUpCastling;
  downCastling = backDownCastling;
  turnChange();
  tesu = tesu - 2;//手数を一手戻す(関数turnChangeで手数+1してあるので、手数を2減らしている)

  canBack = false;//一手戻れるようにしている
}
boolean originalMode;//オリジナル（原型）ルールで始めるための変数
boolean balanceMode;//バランスルールで始めるための変数
boolean customMode;//カスタムルールで始めるための変数
boolean optionMode;//カスタムルールの設定を変えるための変数
boolean explainMode;//説明画面に行くための変数
boolean back; //タイトル画面に戻るかどうかを判断する変数
boolean option1, option2, option3;//設定しようとしているか判断する変数
boolean original_option, balance_option;
boolean start;//ルール確認画面のゲームを始めるボタンに
int option1_num, option2_num, option3_num;//選択肢を表す番号
int change_option1, change_option2, change_option3;//選択肢変更用の変数
boolean canB, canBreakTime;//休憩ボタンを押せるかどうか判定する変数(canBがボタンを押せるかの判定、canBreakTimeが休憩するかの判定)

public void menu() {//メニュー画面を表示する処理(gearは0)
  background(0xFFDEB887);//背景
  textSize(60);
  fill(0);
  text("チェスVS将棋", width/2 - 180, 100);


  originalButton();//オリジナルモードに進むためのボタン
  balanceButton();//バランスモードに進むためのボタン
  customButton();//カスタムモードに進むためのボタン
  optionButton();//カスタムモードの設定画面に進むためのボタン
  explainButton();//特殊ルール説明の画面に行くためのボタン
}


public void play() {//ゲームをプレイする処理(gearは1)
  background(0xFFDEB887);//背景
  //fill(#deb887);
  // rect(stage_x,stage_y,600,600);
  fill(0);
  rect(width-consoleSize, 0, consoleSize, height);
  canPut = false;//駒が動かせるかを判断している変数

  view();//初期画面
  fill(255);
  textSize(25);
  text("対局時間", width-consoleSize + 50, 270);
  viewTimer(width - consoleSize + 62.5f, 300, time);
  text(tesu + "手目", width - consoleSize + 50, 335);

  canB = !(choose) && pop == 0 && !(haveChessChoose) && !(castMode) && !(syogiCastMode)&& !(haveChoose);
  canBreakTime = breakTimeButton(canB);//休憩ボタン
  resignButton(canB);//降参ボタン
  if (canBack) {
    backPieceButton(canB);//一手戻るボタン
  }
  int viewHave;
  int viewHaveChess;
  boolean canH;//他のモードになっていないか判断する変数
  canH =  !(choose) && pop == 0 && !(haveChessChoose) && !(castMode) && !(syogiCastMode);
  if (rules[0]) {
    haveView();//持ち駒を描画する
    viewHave = viewHaveCheck();
    mouseHave = viewHave;//マウスの方の処理を行うために色々やる
    if (viewHave >= 1 && viewHave <= 4 && canH) {
      viewHaveRect(viewHave);
    }
  }

  if (rules[1]) {
    haveChessView();
    viewHaveChess = viewHaveChessCheck();
    mouseHaveChess = viewHaveChess;//マウスの方の処理を行うために色々やる
    if (viewHaveChess >= 5 && viewHaveChess <= 8 && canH) {
      viewHaveChessRect(viewHaveChess);
    }
  }
  canMoveCheck();//どの駒がどこからどこへ動けるか判断する処理
  haveCheck();//持ち駒をどこに置くことができるか判断する処理,チェスの駒の方も包含している
  boolean check;
  check = checkCheck();//チェック、王手確認用処理
  if (check) {
    viewCheck();
  }

  boolean can;
  can = (mouseX>= stage_x && mouseX < stage_x+stage_size) &&(mouseY >= stage_y && mouseY < stage_y + stage_size)
    && !(choose)&& !(haveChoose) && (pop == 0) && !(castMode) &&!(syogiCastMode) && !(syogiCastMode) && !(haveChessChoose);
  if (can) {
    /*↑選択モードでなく,駒を選択しているかの判定*/
    int x, y;
    x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));
    y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
    fill(0, 0, 255, 64);
    rect(stage_x + box_size*x, stage_y + box_size*y, box_size, box_size);//マウスがある位置を塗る
  }
  cast = castlingCheck(turn_num);
  if (cast && upCastling && rules[5] && turn_num == 2) {//チェス側のキャスリング
    castling();
  }
  if (cast && downCastling && rules[4] && turn_num == 1) {//将棋側のキャスリング
    syogiCastling();
  }

  if (choose) {//駒が選択されているときの処理
    //viewChoose(choose_x,choose_y);//選択した駒が動ける範囲に色塗りを行う
    moveView(choose_y, choose_x);
    canPut=canPutCheck(choose_y, choose_x);
  }
  if (haveChoose) {//持ち駒が0だった時の処理
    if (turn_num == 1) {//下側のターン
      if (downHave[mouseHaveOption] == 0) {
        haveChoose =false;
      }
    } else {
      if (upHave[mouseHaveOption] == 0) {
        haveChoose =false;
      }
    }
  }

  if (haveChessChoose) {
    if (turn_num == 1) {//下側のターン
      if (downHaveChess[mouseHaveOption] == 0) {
        haveChessChoose =false;
      }
    } else {
      if (upHaveChess[mouseHaveOption] == 0) {
        haveChessChoose =false;
      }
    }
  }

  if (haveChoose) {//持ち駒が選択されているときの処理
    int x, y;
    x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));
    y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
    haveMoveView(haveX, haveY, have_num, mouseHaveOption);//[viewタブに書いてある]
    canHavePut=canHavePutCheck(y, x);//[hves]タブ,マウスがある位置が黄色になる
  }
  if (haveChessChoose) {//チェスの持ち駒が選択されているときの処理
    int x, y;
    x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));
    y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
    haveChessMoveView(haveX, haveY, have_num, mouseHaveOption);//[viewタブに書いてある]
    canHaveChessPut=canHavePutCheck(y, x);//[hves]タブ,マウスがある位置が黄色になる
  }
  if (pop != 0) {
    switch(pop) {
    case 1:
      anyPopUp();//任意の成り
      break;

    case 2:
      forcedPopUp();//強制の成り
      break;

    case 3:
      pawnPopUp();//ポーンの成り
      break;

    case 4:
      resignPopUp();//降参するかどうかを聞くポップアップ
      break;

    case 5:
      backPopUp();//一手戻るかどうかを聞くポップアップ
      break;

    default:
      break;
    }
  }
  if (castMode) {
    castRect();
  }
  if (syogiCastMode) {
    syogiCastRect();
  }
}

public void gameEnd() {
  if (fixTesu) {
    tesu--;
    fixTesu = false;
  }
  stopTimer();
  background(0);
  fill(120, 120, 25);
  int t_s = 60;
  textSize(t_s);
  if ( win == 1) {
    text("下側陣営(将棋)の勝利", width/2 - 5*t_s, 100);
  } else {
    text("上側陣営(チェス)の勝利", width/2 - 5.5f * t_s, 100);
  }
  t_s = 40;
  textSize(40);
  String moji;
  moji = "対局時間:";
  text(moji, width/2-280, 400);
  viewRightTimer(width/2+200, 400, time, t_s);
  moji = "手数: " ;
  text(moji, width/2-280, 500);
  moji = tesu + "手";
  text(moji, width/2+200 - ((moji.length())/2 * t_s - t_s/2 ), 500);
}

public void option() {//設定の画面
  background(160, 145, 160);
  textSize(60);
  fill(0);
  text("カスタムモード設定", width/2 - 270, 100);
  fill(0);
  textSize(40);
  text("持ち駒", width/2 - 200, 300);
  text("駒の成り", width/2 - 200, 380);
  text("キャスリング", width/2 - 200, 460);

  backButton();
  viewOptionButtons();//設定に使われるボタンの処理
}

public void explain() {//特殊ルールの説明をする処理
  background(0xFFDEB887);
  backButton();
  fill(0);
  textSize(60);
  text("特殊ルールの説明", width/2 - 4*60, 100);
  textSize(30);
  text("チェスの持ち駒:", width/2 - 500, 300);
  text("将棋のキャスリング:", width/2 - 550, 500);
  String chessHaveExplain, syogiCastlingExplain;
  chessHaveExplain ="基本的には将棋と同じですが1つ異なる点があります。\nポーンが成った駒が取られた場合ポーンではなく、\n成った駒として持ち駒になります。";
  syogiCastlingExplain = "チェスでは、キングとルークでキャスリングを行うのに対し、\n将棋では王と香車でキャスリングを行います。";
  textSize(25);
  text(chessHaveExplain, width/2 - 500 + 30*7.5f, 300);
  text(syogiCastlingExplain, width/2 - 550 + 30*9.5f, 500);
}

public void breakTime() {//休憩画面を映す処理
  int t_s;//文字のサイズ
  t_s = 60;
  background(255, 255, 120);
  fill(0);
  textSize(t_s);
  text("休憩中", width/2 - 60*1.5f, 100);
  t_s = 40;
  textSize(t_s);
  String moji;
  moji = "現在の対局時間";
  text(moji, width/2 - 540, 400);
  viewRightTimer(width/2-40, 400, time, t_s);
  moji = "現在の手数";
  text(moji, width/2 - 540, 500); 
  moji = tesu + "手目";
  text(moji, width/2 -40 - ((moji.length()+0.5f)/2 * t_s), 500);

  String[] mojis = {"将棋の持ち駒", "チェスの持ち駒", "将棋の成り", "チェスの成り", "将棋のキャスリング", "チェスのキャスリング"};
  t_s = 40;
  textSize(t_s);
  moji = "ルール確認";
  fill(0);
  text(moji, (width/2) + 300, 250);
  t_s = 30;
  textSize(t_s);
  for (int n = 0; n < mojis.length; n++) {
    fill(0);
    text(mojis[n], (width/2) + 160, 340 + n*60);
    if (rules[n]) {//ルールの確認
      moji = "あり";
    } else {
      moji = "なし";
      fill(255, 0, 0);
    }
    text(moji, (width/2) + 530, 340 + n*60);
  }

  playButton();//ゲームに戻るボタン
}

public void confirm() {//ゲームを始める前にルールの確認をする画面
  background(0xFFDEB887);//背景
  int t_s;
  String moji;
  String[] mojis = {"将棋の持ち駒", "チェスの持ち駒", "将棋の成り", "チェスの成り", "将棋のキャスリング", "チェスのキャスリング"};
  t_s = 60;
  textSize(t_s);
  moji = "ルール確認画面";
  fill(0);
  text(moji, (width/2) - (moji.length()/2 * t_s), 100);
  t_s = 40;
  textSize(t_s);
  for (int n = 0; n < mojis.length; n++) {
    fill(0);
    text(mojis[n], width/4, 240 + n*60);
    if (rules[n]) {//ルールの確認
      moji = "あり";
    } else {
      moji = "なし";
      fill(255, 0, 0);
    }
    text(moji, width/4*3, 240 + n*60);
  }


  backButton();//メニュー画面に戻るための関数
  startButton();//ゲームを始めるためのボタン
}
boolean normalCanPut[][] = new boolean[9][9];
boolean upKeimaCanPut[][] = new boolean[9][9];
boolean downKeimaCanPut[][] = new boolean[9][9];
boolean upKyosyaCanPut[][] = new boolean[9][9];
boolean downKyosyaCanPut[][] = new boolean[9][9];
boolean upHuhyoCanPut[][] = new boolean[9][9];
boolean downHuhyoCanPut[][] = new boolean[9][9];
int haveOption; //選んだ持ち駒の種類が入る

public void initHave() {
  haveChoose = false;
  haveChessChoose = false;
  for (int n = 0; n < upHave.length; n++) {
    upHave[n] = 0;
    downHave[n] = 0;
  }
  for (int n = 0; n < upHaveChess.length; n++) {
    upHaveChess[n] = 0;
    downHaveChess[n] = 0;
  }
  for (int n = 0; n < normalCanPut.length; n++) {
    for (int j = 0; j < normalCanPut[n].length; j++) {
      normalCanPut[n][j] = false;
      upKeimaCanPut[n][j] = false;
      downKeimaCanPut[n][j] = false;
      upKyosyaCanPut[n][j] = false;
      downKyosyaCanPut [n][j] = false;
      upHuhyoCanPut [n][j] = false;
      downHuhyoCanPut [n][j] = false;
    }
  }
}
public void haveView() {
  //持ち駒
  //将棋の下側
  fill(0xFFAAAA00);
  rect(stage_x + box_size*10.25f, stage_y + box_size*5+40, 200, 220);
  for (int n = 0; n < 4; n++) {
    fill(255);
    image(have_images[n], stage_x + box_size*10.5f, stage_y + box_size*6+n*40, 40, 40);
    fill(0);
    if (downHave[n] == 0) {
      fill(255, 0, 0);
    }
    text("×"+downHave[n], stage_x + box_size*10.5f+40, stage_y + box_size*6.5f+n*40);
  }
  for (int n = 0; n < 3; n++) {
    fill(255);
    image(have_images[n+4], stage_x + box_size*12, stage_y + box_size*6+n*40, 40, 40);
    fill(0);
    if (downHave[n+4] == 0) {
      fill(255, 0, 0);
    }
    text("×"+downHave[n+4], stage_x + box_size*12+40, stage_y + box_size*6.5f+n*40);
  }
  /*上側*/
  fill(0xFFAAAA00);
  rect(stage_x + box_size*(-4.25f), stage_y, 200, 220);
  for (int n = 0; n < 4; n++) {
    fill(255);
    image(have_images[n], stage_x + box_size*(-4), stage_y +(1+n)*40, 40, 40);
    fill(0);
    if (upHave[n] == 0) {
      fill(255, 0, 0);
    }
    text("×"+upHave[n], stage_x + box_size*(-4)+40, stage_y +(1+n)*40+box_size*0.5f);
  }
  for (int n = 0; n < 3; n++) {
    fill(255);
    image(have_images[n+4], stage_x + box_size*(-2.5f), stage_y +40+n*40, 40, 40);
    fill(0);
    if (upHave[n+4] == 0) {
      fill(255, 0, 0);
    }
    text("×"+upHave[n+4], stage_x + box_size*(-2.5f)+40, stage_y +(1+n)*40+box_size*0.5f);
  }
}
public void haveChessView() {
  //下側
  fill(0xFFAAAA00);
  rect(stage_x + box_size*10.25f, stage_y + box_size*5-140, 200, 170);
  for (int n = 0; n < 3; n++) {
    fill(255);
    image(down_have_chess[n], stage_x + box_size*10.5f, stage_y + box_size*6+n*40 - 180, 38, 38);
    fill(0);
    if (downHaveChess[n] == 0) {
      fill(255, 0, 0);
    }
    text("×"+downHaveChess[n], stage_x + box_size*10.5f+40, stage_y + box_size*6.5f+n*40 - 180);
  }
  for (int n = 0; n < 2; n++) {
    fill(255);
    image(down_have_chess[n+3], stage_x + box_size*12, stage_y + box_size*6+n*40 - 180, 38, 38);
    fill(0);
    if (downHaveChess[n+3] == 0) {
      fill(255, 0, 0);
    }
    text("×"+downHaveChess[n+3], stage_x + box_size*12+40, stage_y + box_size*6.5f+n*40 - 180);
  }
  /*上側*/
  fill(0xFFAAAA00);
  rect(stage_x + box_size*(-4.25f), stage_y + 230, 200, 170);
  for (int n = 0; n < 3; n++) {
    fill(255);
    image(up_have_chess[n], stage_x + box_size*(-4), stage_y +(1+n)*40 + 220, 38, 38);
    fill(0);
    if (upHaveChess[n] == 0) {
      fill(255, 0, 0);
    }
    text("×"+upHaveChess[n], stage_x + box_size*(-4)+40, stage_y +(1+n)*40+box_size*0.5f + 220);
  }
  for (int n = 0; n < 2; n++) {
    fill(255);
    image(up_have_chess[n+3], stage_x + box_size*(-2.5f), stage_y +40+n*40 + 220, 38, 38);
    fill(0);
    if (upHaveChess[n+3] == 0) {
      fill(255, 0, 0);
    }
    text("×"+upHaveChess[n+3], stage_x + box_size*(-2.5f)+40, stage_y +(1+n)*40+box_size*0.5f + 220);
  }
}
public int[]  have(int[] have_num, int soeji2) {//持ち駒を保存する処理
  if (soeji2 != 0) {
    if ( soeji2 >= 1 && soeji2 <= 7 ) {
      soeji2 = soeji2 - 1;
    } else if (soeji2 >= 8 && soeji2 <= 11) {
      soeji2 = soeji2 -8;
    } else {
      soeji2 = soeji2 - 7;
    }
    have_num[soeji2]++;
  }
  return have_num;
}

public int [] chessHave(int[] have_num, int soeji2) {
  if (soeji2 != 0) {
    soeji2 -= 1;
    have_num[soeji2]++;
  }
  return have_num;
}

public int viewHaveCheck() {
  float checkX, checkY;

  checkX = stage_x + box_size*10.5f;//下側の左
  checkY = stage_y + box_size*6;
  if (mouseX >= checkX && mouseX<= checkX+40 && mouseY >= checkY && mouseY <= checkY + 160) {  
    return 1;
  }

  checkX = checkX + box_size*1.5f;//下側の右
  //checkYは変わらない
  if (mouseX >= checkX && mouseX<= checkX+40 && mouseY >= checkY && mouseY <= checkY + 120) {
    return 2;
  }

  checkX = stage_x + box_size*(-4);//上側の左
  checkY = stage_y + 40;
  if (mouseX >= checkX && mouseX<= checkX+40 && mouseY >= checkY && mouseY <= checkY + 160) {
    return 3;
  }

  checkX = checkX + box_size*1.5f;//上側の右
  //checkYは変わらない
  if (mouseX >= checkX && mouseX<= checkX+40 && mouseY >= checkY && mouseY <= checkY + 120) {
    return 4;
  }
  return 0;//範囲内にマウスがなかったら0が返される
}

public int viewHaveChessCheck() {
  float checkX, checkY;

  checkX = stage_x + box_size*10.5f;//下側の左
  checkY = stage_y + box_size*6 - 180;
  if (mouseX >= checkX && mouseX<= checkX+40 && mouseY >= checkY && mouseY <= checkY+120) {  
    return 5;
  }

  checkX = checkX + box_size*1.5f;//下側の右
  //checkYは変わらない
  if (mouseX >= checkX && mouseX<= checkX+40 && mouseY >= checkY && mouseY <= checkY+80) {

    return 6;
  }

  checkX = stage_x + box_size*(-4);//上側の左
  checkY = stage_y + 260;
  if (mouseX >= checkX && mouseX<= checkX+40 && mouseY >= checkY && mouseY <= checkY+120) {
    return 7;
  }

  checkX = checkX + box_size*1.5f;//上側の右
  //checkYは変わらない
  if (mouseX >= checkX && mouseX<= checkX+40 && mouseY >= checkY && mouseY <= checkY+80) {
    return 8;
  }
  return 0;//範囲内にマウスがなかったら0が返される
}
public void viewHaveRect(int num) {
  float checkX, checkY;
  switch(num) {
  case 1://下側の左
    checkX = stage_x + box_size*10.5f;//下側の左
    checkY = stage_y + box_size*6;
    break;

  case 2://下側の右
    checkX = stage_x + box_size*12;//下側の右
    checkY = stage_y + box_size*6;
    break;

  case 3://上側の左
    checkX = stage_x + box_size*(-4);//上側の左
    checkY = stage_y + 40;
    break;

  case 4://上側の右
    checkX = stage_x + box_size*(-2.5f);//上側の右
    checkY = stage_y + 40;
    break;

  default://ここを通ることは絶対にない
    checkX =0;
    checkY = 0;
    break;
  }
  if (num == 1 || num == 3) {//上でも下で左側の時の処理
    for (int n = 0; n < 4; n++) {
      int j = 3 - n;
      if (mouseY >= checkY + j*40) {
        fill(0, 0, 255, 64);
        if (!(haveChoose)) {
          rect(checkX, checkY + j*40, 40, 40);
        }
        haveOption = j;//現在マウスがいる位置の駒の種類を保存
        break;
      }
    }
  } else {//右側の時の処理
    for (int n = 0; n < 3; n++) {
      int j = 2 - n;
      if (mouseY >= checkY + j*40) {
        fill(0, 0, 255, 64);
        if (!(haveChoose)) {
          rect(checkX, checkY + j*40, 40, 40);
        }
        haveOption = j + 4;//現在マウスがいる位置の駒の種類を保存
        break;
      }
    }
  }
}
public void viewHaveChessRect(int num) {

  float checkX, checkY;
  switch(num) {
  case 5://下側の左
    checkX = stage_x + box_size*10.5f;//下側の左
    checkY = stage_y + box_size*6 - 180;
    break;

  case 6://下側の右
    checkX = stage_x + box_size*12 ;//下側の右
    checkY = stage_y + box_size*6 - 180;
    break;

  case 7://上側の左
    checkX = stage_x + box_size*(-4);//上側の左
    checkY = stage_y + 40+ 220;
    break;

  case 8://上側の右
    checkX = stage_x + box_size*(-2.5f);//上側の右
    checkY = stage_y + 40+ 220;
    break;

  default://ここを通ることは絶対にない
    checkX =0;
    checkY = 0;
    break;
  }
  if (num == 5 || num == 7) {//上でも下で左側の時の処理
    for (int n = 1; n < 4; n++) {
      int j = 3 - n;
      if (mouseY >= checkY + j*40) {
        fill(0, 0, 255, 64);
        if (!(haveChessChoose)) {
          rect(checkX, checkY + j*40, 40, 40);
        }
        haveOption = j;//現在マウスがいる位置の駒の種類を保存
        break;
      }
    }
  } else {//右側の時の処理
    for (int n = 1; n < 3; n++) {
      int j = 2 - n;
      if (mouseY >= checkY + j*40) {
        fill(0, 0, 255, 64);
        if (!(haveChessChoose)) {
          rect(checkX, checkY + j*40, 40, 40);
        }
        haveOption = j + 3;//現在マウスがいる位置の駒の種類を保存
        break;
      }
    }
  }
}

public void haveCheck() {
  for (int n = 0; n < normalCanPut.length; n++) {
    for (int j = 0; j < normalCanPut[n].length; j++) {
      normalCanPut[n][j] = false;
      upKeimaCanPut[n][j] = false;
      downKeimaCanPut[n][j] = false;
      upKyosyaCanPut[n][j] = false;
      downKyosyaCanPut [n][j] = false;
      upHuhyoCanPut [n][j] = false;
      downHuhyoCanPut [n][j] = false;
    }
  }
  for (int n = 0; n < normalCanPut.length; n++) {
    for (int j = 0; j < normalCanPut[n].length; j++) {
      if (stage_piece_num[n][j] == 0) {
        normalCanPut[n][j] = true;
        if (n>=1) {//下側の香車と歩兵
          downKyosyaCanPut[n][j] = true;
          boolean huhyoCheck;
          huhyoCheck = true;
          for (int i = 0; i < 9; i++) {
            if (stage_piece_num[i][j] == 101) {
              huhyoCheck = false;
              break;
            }
          }
          downHuhyoCanPut[n][j] = huhyoCheck;
        }
        if (n>=2) {//下側の桂馬
          downKeimaCanPut[n][j] = true;
        }
        if (n<=7) {//上側の香車と歩兵
          upKyosyaCanPut[n][j] = true;
          boolean huhyoCheck;
          huhyoCheck = true;
          for (int i = 0; i < 9; i++) {
            if (stage_piece_num[i][j] == 201) {
              huhyoCheck = false;
              break;
            }
          }
          upHuhyoCanPut[n][j] = huhyoCheck;
        }
        if (n<=6) {//上側の桂馬
          upKeimaCanPut[n][j] = true;
        }
      }
    }
  }
}


public boolean canHavePutCheck(int y, int x) {//置くことができる駒にマウスがあったら色を塗りtrueを返す
  boolean canPut;

  canPut = false;
  if (mouseX >= stage_x && mouseY >= stage_y) {
    if (x >= 0 && x <= 8 && y >= 0 && y <= 8) {
      if (canPuts[PApplet.parseInt(y)][PApplet.parseInt(x)]) {
        fill(0, 255, 0, 80);
        rect(stage_x + box_size*x, stage_y + box_size*y, box_size, box_size);
        canPut = true;
      }
    }
  }

  return canPut;
}

public void havePlace(int y, int x, int ex_option) {
  backSave();//一手戻るために記録をしている
  int koma;
  int option;
  option = ex_option + 1;
  koma = turn_num*100 + option;
  stage_piece_num[y][x] = koma;
  haveChoose = false;
  canHavePut = false;
  if (turn_num == 1) {
    downHave[ex_option]--;
  } else {
    upHave[ex_option]--;
  }
  turnChange();
}

public void haveChessPlace(int y, int x, int ex_option) {
  backSave();//一手戻るために記録をしている
  int koma;
  int option;
  option = ex_option + 11;
  koma = turn_num*100 + option;
  stage_piece_num[y][x] = koma;
  haveChessChoose = false;
  canHaveChessPut = false;
  if (turn_num == 1) {
    downHaveChess[ex_option]--;
  } else {
    upHaveChess[ex_option]--;
  }
  turnChange();
}
PImage[] syogi_images = new PImage[14];//通常の将棋の駒
PImage[] reverse_images = new PImage[14];//上側で表示される将棋(王が上に来ることはないので[0]番は使われない)
PImage[] chess_images = new PImage[6];//通常のチェスの駒
PImage[] reverse_chess = new PImage[6];//下側のチェスの駒(キングが下に来ることはないので[0]番目は使われない)
PImage[] have_images = new PImage[7];//将棋の持ち駒の画像
PImage[] up_have_chess = new PImage[5];//上側のチェスの持ち駒の画像
PImage[] down_have_chess = new PImage[5];//チェスの持ち駒の画像
public void initImage() {

  syogi_images[0]= loadImage("data/image/将棋/王.png");
  syogi_images[1]= loadImage("data/image/将棋/歩兵.png");
  syogi_images[2]= loadImage("data/image/将棋/香車.png");
  syogi_images[3]= loadImage("data/image/将棋/桂馬.png");
  syogi_images[4]= loadImage("data/image/将棋/銀将.png");
  syogi_images[5]= loadImage("data/image/将棋/金将.png");
  syogi_images[6]= loadImage("data/image/将棋/角行.png");
  syogi_images[7]= loadImage("data/image/将棋/飛車.png");
  syogi_images[8]= loadImage("data/image/将棋/と金.png");
  syogi_images[9]= loadImage("data/image/将棋/成り香.png");
  syogi_images[10]= loadImage("data/image/将棋/成り桂.png");
  syogi_images[11]= loadImage("data/image/将棋/成り銀.png");
  syogi_images[12]= loadImage("data/image/将棋/竜馬.png");
  syogi_images[13]= loadImage("data/image/将棋/龍王.png");
  for (int n = 0; n < syogi_images.length; n++) {
    syogi_images[n].resize(60, 60);
  }
  reverse_images[1] = loadImage("data/image/反転/反転歩兵.png");
  reverse_images[2] = loadImage("data/image/反転/反転香車.png");
  reverse_images[3] = loadImage("data/image/反転/反転桂馬.png");
  reverse_images[4] = loadImage("data/image/反転/反転銀将.png");
  reverse_images[5] = loadImage("data/image/反転/反転金将.png");
  reverse_images[6] = loadImage("data/image/反転/反転角行.png");
  reverse_images[7] = loadImage("data/image/反転/反転飛車.png");
  reverse_images[8] = loadImage("data/image/反転/反転と金.png");
  reverse_images[9] = loadImage("data/image/反転/反転成り香.png");
  reverse_images[10] = loadImage("data/image/反転/反転成り桂.png");
  reverse_images[11] = loadImage("data/image/反転/反転成り銀.png");
  reverse_images[12] = loadImage("data/image/反転/反転竜馬.png");
  reverse_images[13] = loadImage("data/image/反転/反転龍王.png");
  for (int n = 1; n < syogi_images.length; n++) {
    reverse_images[n].resize(60, 60);
  }


  chess_images[0] = loadImage("data/image/チェス/キング.png");
  chess_images[1] = loadImage("data/image/チェス/ポーン.png");
  chess_images[2] = loadImage("data/image/チェス/ルーク.png");
  chess_images[3] = loadImage("data/image/チェス/ナイト.png");
  chess_images[4] = loadImage("data/image/チェス/ビショップ.png");
  chess_images[5] = loadImage("data/image/チェス/クイーン.png");
  for (int n = 0; n < chess_images.length; n++) {
    chess_images[n].resize(60, 60);//サイズの変更
  }

  reverse_chess[1] = loadImage("data/image/反転チェス/反転ポーン.png");
  reverse_chess[2] = loadImage("data/image/反転チェス/反転ルーク.png");
  reverse_chess[3] = loadImage("data/image/反転チェス/反転ナイト.png");
  reverse_chess[4] = loadImage("data/image/反転チェス/反転ビショップ.png");
  reverse_chess[5] = loadImage("data/image/反転チェス/反転クイーン.png");
  for (int n = 1; n < reverse_chess.length; n++) {
    reverse_chess[n].resize(60, 60);//サイズの変更
  }
  have_images[0]= loadImage("data/image/将棋/歩兵.png");
  have_images[1]= loadImage("data/image/将棋/香車.png");
  have_images[2]= loadImage("data/image/将棋/桂馬.png");
  have_images[3]= loadImage("data/image/将棋/銀将.png");
  have_images[4]= loadImage("data/image/将棋/金将.png");
  have_images[5]= loadImage("data/image/将棋/角行.png");
  have_images[6]= loadImage("data/image/将棋/飛車.png");
  for (int n = 0; n < have_images.length; n++) {
    have_images[n].resize(40, 40);//持ち駒用のサイズ
  }

  up_have_chess[0] = loadImage("data/image/チェス/ポーン.png");
  up_have_chess[1] = loadImage("data/image/チェス/ルーク.png");
  up_have_chess[2] = loadImage("data/image/チェス/ナイト.png");
  up_have_chess[3] = loadImage("data/image/チェス/ビショップ.png");
  up_have_chess[4] = loadImage("data/image/チェス/クイーン.png");
  for (int n = 0; n < up_have_chess.length; n++) {
    up_have_chess[n].resize(40, 40);//持ち駒用のサイズ
  }

  down_have_chess[0] = loadImage("data/image/反転チェス/反転ポーン.png");
  down_have_chess[1] = loadImage("data/image/反転チェス/反転ルーク.png");
  down_have_chess[2] = loadImage("data/image/反転チェス/反転ナイト.png");
  down_have_chess[3] = loadImage("data/image/反転チェス/反転ビショップ.png");
  down_have_chess[4] = loadImage("data/image/反転チェス/反転クイーン.png");
  for (int n = 0; n < down_have_chess.length; n++) {
    down_have_chess[n].resize(40, 40);//サイズの変更
  }
}
public void mousePressed() {//マウスをクリックしたときの処理
  if (gear == 0) {//メニュー画面でのボタン等の処理
    if (originalMode) {//オリジナルモードでゲームを始める
      gear = 2;
    }
    if (balanceMode) {//バランスモードでゲームを始める
      gear = 3;
    }
    if (customMode) {//カスタムモードでゲームを始める
      gear = 4;
    }
    if (optionMode) {//設定モードに遷移する
      gear = 6;
    }
    if (explainMode) {//説明モードに遷移する
      gear = 7;
    }
  }

  if (gear == 1) {//ゲームプレイ中のボタン等の処理
    if (choose) {
      if (!(canPutCheck(choose_y, choose_x))) {
        choose = false;
      }
    }
    if (haveChoose) {
      int x, y;
      x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));
      y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
      if (!(canHavePutCheck(y, x))) {
        haveChoose = false;
      }
    }
    if (haveChessChoose) {
      int x, y;
      x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));
      y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
      if (!(canHavePutCheck(y, x))) {
        haveChessChoose = false;
      }
    }
    if (!(kingSide) && !(queenSide) && (castMode)) {
      castMode = false;
    }
    if (!(rightSide) && !(leftSide) && (syogiCastMode)) {
      syogiCastMode = false;
    }

    if ((mouseX>= stage_x && mouseX < stage_x+stage_size) &&(mouseY >= stage_y && mouseY < stage_y + stage_size)
      && !(choose) && !(haveChoose) && pop == 0 && !(castMode) && !(syogiCastMode)) {
      int x, y;
      x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));
      y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
      boolean turn;
      turn = turnCheck(y, x, turn_num);
      if (stage_piece_num[y][x] != 0 && turn) {//もし駒があったらここの処理が行われる
        move(x, y);
      }
    }

    if (canPut) {//実際に駒を動かすときの処理
      int x, y;
      x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));
      y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
      place(choose_y, choose_x, y, x);//駒を動かす関数
      move_piece_sound.play(0);//駒を指すときの音を流す
    }

    if (canHavePut) {
      int x, y;
      x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));
      y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
      havePlace(y, x, mouseHaveOption);//[haves]タブ
      move_piece_sound.play(0);//駒を指すときの音を流す
    }
    if (canHaveChessPut) {
      int x, y;
      x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));
      y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
      haveChessPlace(y, x, mouseHaveOption);//[haves]タブ
      move_piece_sound.play(0);//駒を指すときの音を流す
    }
    /*持ち駒の処理*/
    if (pop == 0 && turn_num == 1&&(mouseHave==1 || mouseHave == 2)) {
      haveX = mouseX;//持ち駒選択時のマウスの位置を保存する
      haveY = mouseY;
      have_num = mouseHave;
      mouseHaveOption = haveOption;//マウスをクリックしたときの駒の種類が描画される
      haveChoose = true;
    }
    if (pop == 0 && turn_num == 2 &&(mouseHave == 3 || mouseHave == 4)) {
      haveX = mouseX;//持ち駒選択時のマウスの位置を保存する
      haveY = mouseY;
      have_num = mouseHave;
      mouseHaveOption = haveOption;//マウスをクリックしたときの駒の種類が描画される
      haveChoose = true;
    }

    if (pop == 0 && turn_num == 1&&(mouseHaveChess==5 || mouseHaveChess == 6)) {
      haveX = mouseX;//持ち駒選択時のマウスの位置を保存する
      haveY = mouseY;
      have_num = mouseHaveChess;
      mouseHaveOption = haveOption;//マウスをクリックしたときの駒の種類が描画される
      haveChessChoose = true;
    }
    if (pop == 0 && turn_num == 2 &&(mouseHaveChess == 7 || mouseHaveChess == 8)) {
      haveX = mouseX;//持ち駒選択時のマウスの位置を保存する
      haveY = mouseY;
      have_num = mouseHaveChess;
      mouseHaveOption = haveOption;//マウスをクリックしたときの駒の種類が描画される
      haveChessChoose = true;
    }



    /*駒が成るときの処理*/
    if (pop == 1 && popCheck == 1) {
      promotion(proPiece, popCheck);
      pop = 0;
      popCheck = 0;
      turnChange();
    }
    if (pop == 1 && popCheck ==2) {
      pop = 0;
      popCheck = 0;
      turnChange();
    }
    if (pop == 2 && popCheck == 1) {
      promotion(proPiece, popCheck);
      pop = 0;
      popCheck = 0;
      turnChange();
    }
    if (pop == 3 && popCheck != 0) {
      promotion(proPiece, popCheck);
      pop = 0;
      popCheck = 0;
      turnChange();
    }
    /*降参のときの処理*/
    if (resign) {
      pop = 4;
    }
    if (canBackCheck) {
      pop = 5;
    }
    if (pop == 4 && popCheck == 1) {
      turnChange();
      win = turn_num;
      gear = 5;
      popCheck = 0;
    } else if (pop == 4 && popCheck == 2) {
      pop = 0;
      popCheck = 0;
    }
    if (pop == 5 && popCheck == 1) {
      backPiece();
      popCheck = 0;
      pop = 0;
    } else if (pop == 5 && popCheck == 2) {
      pop = 0;
      popCheck = 0;
    }
    /*キャスリングの処理*/
    if (canCastling) {
      castMode = true;
    }
    if (kingSide) {
      kingSideCastling();
      upCastling = false;
      castMode = false;
      kingSide = false;
      queenSide = false;
      turnChange();
    }
    if (queenSide) {
      queenSideCastling();
      upCastling = false;
      castMode = false;
      kingSide = false;
      queenSide = false;
      turnChange();
    }
    //将棋のキャスリング
    if (canSyogiCastling) {
      syogiCastMode = true;
    }
    if (leftSide) {
      leftSideCastling();
      downCastling = false;
      syogiCastMode = false;
      leftSide = false;
      rightSide = false;
      turnChange();
    }
    if (rightSide) {
      rightSideCastling();
      downCastling = false;
      syogiCastMode = false;
      leftSide = false;
      rightSide = false;
      turnChange();
    }
    if (canBreakTime) {
      gear = 8;
      stopTimer();
      canBreakTime = false;
    }
  }
  if (gear == 6) {
    if (back) {
      gear = 0;
      back = false;
    }

    if (option1) {
      option1_num = change_option1;
    }
    if (option2) {
      option2_num = change_option2;
    }
    if (option3) {
      option3_num = change_option3;
    }
    if (original_option) {
      option1_num = 2;
      option2_num = 1;
      option3_num = 3;
    }
    if (balance_option) {
      option1_num = 1;
      option2_num = 2;
      option3_num = 1;
    }
  }
  if (gear ==7) {
    if (back) {
      gear = 0;
      back = false;
    }
  }
  if (gear == 8) {
    if (backPlay) {
      gear = 1;
      startTimer();
      backPlay = false;
    }
  }
  if (gear == 9) {
    if (back) {
      gear = 0;
      back = false;
    }
    if (start) {
      gear = 1;
      start = false;
    }
  }
}
int movedPiece[][][][];//将棋とチェスの動きをひとまとめにする
int syogiMove[][][];//3次元配列(1次元配列に2次元配列を入れるイメージで使用)
int chessMove[][][];
int reverseMove[][][];//上側に表示される将棋の動き
int reverseChessMove[][][];//下側に表示されるチェスの動き
int movePattern[][];//駒の動きを翻訳するために使用する
boolean firstPawn;//ポーンが初めの1歩かどうかを判断する変数

int upCanMove[][][][] = new int[9][9][32][2];//上側陣営の動きを表す配列
int downCanMove[][][][] = new int[9][9][32][2];//下側陣営の動きを表す配列
String test[] = {"歩:", "香車:", "桂馬:", "銀将:", "金将:", "角行:", "飛車:"};
String testChess[] = {"ポーン:", "ルーク:", "ナイト:", "ビショップ:", "クイーン:"};
boolean firstPawns[] = new boolean[8];
public void initMove() {
  for (int n = 0; n < firstPawns.length; n++) {//ポーンの一歩目ができるかどうかを確認する変数
    firstPawns[n] = true;
  }
  /*{向き,歩数}(向きは左前を0として半時計回り
   歩数は1が1歩、2が無限歩),桂馬やナイト、ポーンは
   少し特殊なので別で作る*/

  /*まずは将棋の動きから*/
  int syogi_ou[][] ={{0, 1}, {1, 1}, {2, 1}, {3, 1}, {4, 1}, {5, 1}, {6, 1}, {7, 1}};//王の動きを表している
  int syogi_hu[][] ={{1, 1}};//歩の動き
  int syogi_kyo[][] ={{1, 2}};//香車の動き
  int syogi_kei[][]={{-1, -2}, {1, -2}};//桂馬は{xの歩数,yの歩数}
  int syogi_gin[][] ={{0, 1}, {1, 1}, {2, 1}, {4, 1}, {6, 1}};//銀の動き
  int syogi_kin[][] = {{0, 1}, {1, 1}, {2, 1}, {3, 1}, {5, 1}, {7, 1}};//金、と金、成り香、成り桂、成り銀の動き
  int syogi_kaku[][] ={{0, 2}, {2, 2}, {4, 2}, {6, 2}};//角行の動き
  int syogi_hisya[][] = {{1, 2}, {3, 2}, {5, 2}, {7, 2}};//飛車の動き
  int syogi_ryuuma[][] ={{0, 2}, {1, 1}, {2, 2}, {3, 1}, {4, 2}, {5, 1}, {6, 2}, {7, 1}};//竜馬(成り角の動き)
  int syogi_ryuuou[][] = {{0, 1}, {1, 2}, {2, 1}, {3, 2}, {4, 1}, {5, 2}, {6, 1}, {7, 2}};//龍王(成り飛車の動き)
  int ex_syogiMove[][][] = {syogi_ou, syogi_hu, syogi_kyo, syogi_kei, syogi_gin, //長すぎるので改行
    syogi_kin, syogi_kaku, syogi_hisya, syogi_kin, syogi_kin, syogi_kin, syogi_kin, syogi_ryuuma, syogi_ryuuou};
  syogiMove = ex_syogiMove;//グローバル変数に将棋の駒の動きを入れる

  /*上側陣営の将棋の動き*/
  int space[][] ={{0, 0}};//上側には王がいないので仮置き
  int reverse_hu[][] ={{5, 1}};//歩の動き
  int reverse_kyo[][] ={{5, 2}};//香車の動き
  int reverse_kei[][]={{-1, 2}, {1, 2}};//桂馬は{xの歩数,yの歩数}
  int reverse_gin[][] ={{0, 1}, {2, 1}, {4, 1}, {5, 1}, {6, 1}};//銀の動き
  int reverse_kin[][] = {{1, 1}, {3, 1}, {4, 1}, {5, 1}, {6, 1}, {7, 1}};//金、と金、成り香、成り桂、成り銀の動き
  int reverse_kaku[][] ={{0, 2}, {2, 2}, {4, 2}, {6, 2}};//角行の動き
  int reverse_hisya[][] = {{1, 2}, {3, 2}, {5, 2}, {7, 2}};//飛車の動き
  int reverse_ryuuma[][] ={{0, 2}, {1, 1}, {2, 2}, {3, 1}, {4, 2}, {5, 1}, {6, 2}, {7, 1}};//竜馬(成り角の動き)
  int reverse_ryuuou[][] = {{0, 1}, {1, 2}, {2, 1}, {3, 2}, {4, 1}, {5, 2}, {6, 1}, {7, 2}};//龍王(成り飛車の動き)
  int ex_reverseMove[][][] = {space, reverse_hu, reverse_kyo, reverse_kei, reverse_gin, //長すぎるので改行
    reverse_kin, reverse_kaku, reverse_hisya, reverse_kin, reverse_kin, reverse_kin, reverse_kin, reverse_ryuuma, reverse_ryuuou};
  reverseMove = ex_reverseMove;

  /*次はチェス*/
  int chess_king[][] = syogi_ou;//将棋の王と同じ
  int chess_pawn[][] = {{0, 1}, {0, 2}, {-1, 1}, {1, 1}};//左からいつもの、初めの一歩、敵が斜め前にいるとき、敵が斜め前にいるとき
  /*ポーンは桂馬やナイトと同じ動かし方をする*/
  int chess_rook[][] = syogi_hisya;//ルークの動きは将棋の飛車と同じ
  int chess_knight[][] = {{-1, -2}, {1, -2}, {2, -1}, {2, 1}, {1, 2}, {-1, 2}, {-2, 1}, {-2, -1}};//ナイトは{xの歩数,yの歩数}
  int chess_bishop[][] = syogi_kaku;//ビショップの動きは将棋の角行と同じ
  int chess_queen[][]= {{0, 2}, {1, 2}, {2, 2}, {3, 2}, {4, 2}, {5, 2}, {6, 2}, {7, 2}};//クイーンの動き
  int ex_chessMove[][][] = {chess_king, chess_pawn, chess_rook, chess_knight, chess_bishop, chess_queen};
  chessMove = ex_chessMove;//グローバル変数にチェスの駒の動きを入れる

  /*下側のチェスの動き(ほとんど元のチェスト同じ)*/
  int reverse_pawn[][] ={{0, -1}, {0, -2}, {-1, -1}, {1, -1}};//[1]番目は実は必要ないが関数の関係で必要
  int ex_reverse_chess[][][] = {space, reverse_pawn, chess_rook, chess_knight, chess_bishop, chess_queen};
  reverseChessMove = ex_reverse_chess;//グローバル変数に駒の動きを入れる
  int ex_movedPiece[][][][] = {syogiMove, chessMove, reverseMove, reverseChessMove};//[将棋かチェスか上側陣営の将棋か下側のチェス][種類][駒の動きの種類][実際の動き]
  movedPiece = ex_movedPiece;//将棋とチェスの動きを組み合わせる

  int ex_movePattern[][] = {{-1, -1}, {0, -1}, {1, -1}, {1, 0}, {1, 1}, {0, 1}, {-1, 1}, {-1, 0}};//翻訳するための前準備(x,y)
  movePattern = ex_movePattern;//駒の動きを翻訳するときに使う変数

  for (int n = 0; n < upCanMove.length; n++) {
    for (int j = 0; j < upCanMove[n].length; j++) {
      for (int i = 0; i < upCanMove[n][j].length; i++) {
        for (int k = 0; k < upCanMove[n][j][i].length; k++) {
          upCanMove[n][j][i][k] = -1;
        }
      }
    }
  }
  for (int n = 0; n < downCanMove.length; n++) {
    for (int j = 0; j < downCanMove[n].length; j++) {
      for (int i = 0; i < downCanMove[n][j].length; i++) {
        for (int k = 0; k < downCanMove[n][j][i].length; k++) {
          downCanMove[n][j][i][k] = -1;
        }
      }
    }
  }
}

public void canMoveCheck() {//駒がどこからどこに動けるかを陣営ごとに記述する←超大事!!
  for (int n = 0; n < upCanMove.length; n++) {
    for (int j = 0; j < upCanMove[n].length; j++) {
      for (int i = 0; i < upCanMove[n][j].length; i++) {
        for (int k = 0; k < upCanMove[n][j][i].length; k++) {
          upCanMove[n][j][i][k] = -1;//変数の初期化
        }
      }
    }
  }
  for (int n = 0; n < downCanMove.length; n++) {
    for (int j = 0; j < downCanMove[n].length; j++) {
      for (int i = 0; i < downCanMove[n][j].length; i++) {
        for (int k = 0; k < downCanMove[n][j][i].length; k++) {
          downCanMove[n][j][i][k] = -1;//変数の初期化
        }
      }
    }
  }

  for (int n = 0; n < stage_piece_num.length; n++) {
    for (int j = 0; j < stage_piece_num[n].length; j++) {//「どこから動くか」を中心にする,n→y座標,j→x座標
      if (stage_piece_num[n][j] != 0) {//駒がなかったら処理しない
        int soeji[];
        soeji = bunnkai(stage_piece_num[n][j]);//数字が分解される
        if (soeji[0] == 1) {//下側陣営のとき
          if (soeji[1] == 1 && soeji[2] == 1) {//下側のポーンの動き
            downCanMove[n][j] = pawnMove(n, j, soeji);
          } else if (soeji[2] == 3) {//桂馬とナイトの駒のとき
            downCanMove[n][j] = jumpMove(n, j, soeji);
          } else {//通常の駒の処理

            downCanMove[n][j] = normalMove(n, j, soeji);//下側陣営の通常の駒の動きを絶対参照方式で入れる
          }
        } else {//上側陣営のときの処理


          if (soeji[2] == 1 && soeji[1] == 1) {//ポーンの駒の処理
            upCanMove[n][j] = pawnMove(n, j, soeji);
          } else if (soeji[2] == 3) {//ナイトの駒の処理
            upCanMove[n][j] = jumpMove(n, j, soeji);
          } else {//通常の駒の処理

            upCanMove[n][j] =normalMove(n, j, soeji);
          }
        }
      }
    }
  }
}

public int[][] normalMove(int y, int x, int soeji[]) {//通常の駒
  int soeji1, soeji2, soeji3;
  soeji1 = soeji[0];//陣営情報
  soeji2 = soeji[1];//チェスか将棋かの情報
  soeji3 = soeji[2];//駒の種類
  if (soeji1 == 2 && soeji2 == 0) {
    soeji2 = 2;
  } else if (soeji1 == 1 && soeji2 ==1) {
    soeji2 = 3;
  }

  int m_y, m_x;//参照するときに使う
  m_y = y;//選択された駒の位置を保存
  m_x = x;//選択された駒野位置を保存

  int size;
  size = 32;
  int insert[][] = new int[size][2];//代入用配列
  for (int n = 0; n < insert.length; n++) {
    for (int j = 0; j < insert[n].length; j++) {
      insert[n][j] = -1;
    }
  }
  int count = 0;
  for (int n = 0; n < movedPiece[soeji2][soeji3].length; n++) {//駒が動ける動きを配列に入れる処理
    int transration[];
    int moves[];
    boolean enemy = true;//駒に敵がいたら[false]になる
    moves = movedPiece[soeji2][soeji3][n];//サイズは2,内容は(方向,歩数),歩数は1で1歩、2で無限歩
    transration = movePattern[moves[0]];//方向を翻訳して代入
    m_x = m_x + transration[0];
    m_y = m_y + transration[1];//1マス動く
    if (canMove(m_y, m_x, soeji1)) {
      insert[count][0] = m_y;
      insert[count][1] = m_x;
      enemy = enemyCheck(m_y, m_x, soeji1);
      count += 1;
      m_x = m_x + transration[0];
      m_y = m_y + transration[1];

      while (canMove(m_y, m_x, soeji1) && moves[1] == 2 && enemy) {
        insert[count][0] = m_y;
        insert[count][1] = m_x;
        enemy = enemyCheck(m_y, m_x, soeji1);
        count += 1;
        m_x = m_x + transration[0];
        m_y = m_y + transration[1];
      }
    }
    m_y = y;//選択された駒の位置を保存
    m_x = x;//選択された駒野位置を保存
  }
  return insert;
}


public int[][] jumpMove(int y, int x, int soeji[]) {//桂馬とナイトの処理
  int soeji1, soeji2, soeji3;
  soeji1 = soeji[0];//陣営情報
  soeji2 = soeji[1];//チェスか将棋かの情報
  soeji3 = soeji[2];//駒の種類
  if (soeji1 == 2 && soeji2 == 0) {
    soeji2 = 2;
  } else if (soeji1 == 1 && soeji2 ==1) {
    soeji2 = 3;
  }

  int m_y, m_x;//参照するときに使う
  m_y = y;//選択された駒の位置を保存
  m_x = x;//選択された駒野位置を保存

  int size;
  size = 32;
  int insert[][] = new int[size][2];//代入用配列
  for (int n = 0; n < insert.length; n++) {
    for (int j = 0; j < insert[n].length; j++) {
      insert[n][j] = -1;//配列の初期化
    }
  }

  int count = 0;
  for (int n = 0; n < movedPiece[soeji2][soeji3].length; n++) {//駒が動ける動きを配列に入れる処理
    int moves[];//桂馬とナイトは駒の実際の動きが入る
    moves = movedPiece[soeji2][soeji3][n];
    m_x = m_x + moves[0];
    m_y = m_y + moves[1];
    if (canMove(m_y, m_x, soeji1)) {
      insert[count][0] = m_y;
      insert[count][1] = m_x;
      count += 1;
    }

    m_y = y;//選択された駒の位置を保存
    m_x = x;//選択された駒野位置を保存
  }

  return insert;
}


public int[][] pawnMove(int y, int x, int soeji[]) {//ポーンの処理
  int soeji1, soeji2, soeji3;
  soeji1 = soeji[0];//陣営情報
  soeji2 = soeji[1];//チェスか将棋かの情報
  soeji3 = soeji[2];//駒の種類
  if (soeji1 == 1 && soeji2 ==1) {
    soeji2 = 3;
  }

  int m_y, m_x;//参照するときに使う
  m_y = y;//選択された駒の位置を保存
  m_x = x;//選択された駒野位置を保存

  int size;
  size = 32;
  int insert[][] = new int[size][2];//代入用配列
  for (int n = 0; n < insert.length; n++) {
    for (int j = 0; j < insert[n].length; j++) {
      insert[n][j] = -1;//配列の初期化
    }
  }

  int count = 0;
  boolean enemy = true;//敵がいたらtrueになる
  int moves[];//ポーンの動きはそのまま入る
  moves = movedPiece[soeji2][soeji3][0];
  m_x = m_x + moves[0];
  m_y = m_y + moves[1];
  enemy = enemyCheck(m_y, m_x, soeji1);
  if (canMove(m_y, m_x, soeji1)&& (enemy)) {
    insert[count][0] = m_y;
    insert[count][1] = m_x;
    //そのマスに敵がいるかの確認
    count += 1;
    m_y = y;//選択された駒の位置を保存
    m_x = x;//選択された駒野位置を保存
    moves = movedPiece[soeji2][soeji3][1];//ポーンが初期位置で目の前に敵がいない時
    m_x = m_x + moves[0];
    m_y = m_y + moves[1];
    enemy =enemyCheck(m_y, m_x, soeji1);
    if (enemy && y == 1 && x >= 0 && x <= 7 && canMove(m_y, m_x, soeji1) && firstPawns[x] ) {//ポーンが初期位置にいるとき

      insert[count][0] = m_y;
      insert[count][1] = m_x;
      count += 1;
    }
  }
  m_y = y;//選択された駒の位置を保存
  m_x = x;//選択された駒野位置を保存

  moves = movedPiece[soeji2][soeji3][2];
  m_x = m_x + moves[0];
  m_y = m_y + moves[1];
  if (canMove(m_y, m_x, soeji1)) {
    enemy = enemyCheck(m_y, m_x, soeji1);
    if (!(enemy)) {
      insert[count][0] = m_y;
      insert[count][1] = m_x;
      count += 1;
    }
  }
  m_y = y;//選択された駒の位置を保存
  m_x = x;//選択された駒野位置を保存

  moves = movedPiece[soeji2][soeji3][3];
  m_x = m_x + moves[0];
  m_y = m_y + moves[1];
  if (canMove(m_y, m_x, soeji1)) {
    enemy = enemyCheck(m_y, m_x, soeji1);
    if (!(enemy)) {
      insert[count][0] = m_y;
      insert[count][1] = m_x;
      count += 1;
    }
  }

  return insert;
}

public boolean canMove(int m_y, int m_x, int soeji1) {//そのマスが外ではない(かつ)その駒に味方がいない
  int soeji[];
  if (m_y >= 0 && m_y <= 8 && m_x >= 0 && m_x <= 8) {//マスが外ではない
    soeji = bunnkai(stage_piece_num[m_y][m_x]);
    if (soeji1 != soeji[0]) {//その駒に味方がいない
      return true;
    }
    //味方がいた場合
    return false;
  }
  return false;//マスの外側だった時
}

public boolean enemyCheck(int m_y, int m_x, int soeji1) {//その駒に敵がいるかの確認
  if (m_y>=0 && m_y <= 8&& m_x >= 0&& m_x <= 8) {
    if (stage_piece_num[m_y][m_x] != 0) {
      boolean check;
      int group;
      int soeji[];
      soeji = bunnkai(stage_piece_num[m_y][m_x]);//動く予定位置にいる駒がわかる
      if (soeji1 != soeji[0]) {//敵がいたら
        check = false;
      } else {
        check = true;
      }

      return check;//駒がいたときはここ
    }
  }
  return true;//駒がないときはここ
}

public void place(int ex_y, int ex_x, int after_y, int after_x) {//駒を動かすときの処理←超重要
  backSave();//一手戻るために記録をしている
  int soeji[];
  int ex_soeji[];
  int check_num;
  check_num = stage_piece_num[after_y][after_x];//動く先の駒が入る(持ち駒保存用)
  ex_soeji = bunnkai(stage_piece_num[ex_y][ex_x]);
  soeji = bunnkai(stage_piece_num[after_y][after_x]);//ここで動く先の駒を分解して添え字にしている
  stage_piece_num[after_y][after_x] = stage_piece_num[ex_y][ex_x];
  stage_piece_num[ex_y][ex_x] = 0;
  choose = false;
  canPut = false;//ここはいらないかも
  if (ex_y == 1 && ex_x >= 0 && ex_x <= 7) {//ポーンが初期位置から動いたからfalseになる
    firstPawns[ex_x] = false;
  }
  if (after_y == 1 && after_x >= 0 && after_x <= 7) {
    firstPawns[after_x] = false;
  }

  if (rules[0]) {
    if (soeji[1] == 0 && check_num !=0) {
      if (turn_num == 1 ) {//下のターン
        downHave = have(downHave, soeji[2]);//soeji[2]には動いた先の駒の種類が入る
        for (int n = 0; n < downHave.length; n++) {
        }
      } else {//上のターン
        upHave = have(upHave, soeji[2]);
        for (int n = 0; n < upHave.length; n++) {
        }
      }
    }
  }
  if (rules[1]) {
    if (soeji[1] == 1 && check_num !=0) {
      if (turn_num == 1 ) {//下のターン
        downHaveChess = chessHave(downHaveChess, soeji[2]);//soeji[2]には動いた先の駒の種類が入る
        for (int n = 0; n < downHaveChess.length; n++) {
        }
      } else {//上のターン
        upHaveChess = chessHave(upHaveChess, soeji[2]);
        for (int n = 0; n < upHaveChess.length; n++) {
        }
      }
    }
  }
  if (rules[4]) {
    if (ex_y == 0 && (ex_x == 0 || ex_x == 4 || ex_x == 7)) {
      castlingChange( ex_x);
    }
    if (after_y == 0 && (after_x == 0 || after_x == 4 || after_x == 7)) {
      castlingChange(after_x);
    }
  }
  if (rules[5]) {
    if (ex_y == 8 && (ex_x == 0 || ex_x == 4 || ex_x == 7)) {
      syogiCastlingChange(ex_x);
    }
    if (after_y == 8 && (after_x == 0 || after_x == 4 || after_x == 7)) {
      syogiCastlingChange(after_x);
    }
  }


  pop = popCheck(stage_piece_num[after_y][after_x], after_y, after_x, ex_y);
  if (pop == 0) {
    turnChange();
  }
  if (check_num == 100) {
    win = 2;
    gear = 5;
  } else if ( check_num == 210) {
    win = 1;
    gear = 5;
  }
}
float[][] anyRectInformations;//任意の成りの座標などの情報が入る
float[] forcedRectInformations;//強制の成りの座標などの情報が入る
float[][] pawnRectInformations;//ポーンのプロモーションの座標などの情報が入る
float[][] resignRectInformations;//降参するボタンなどの座標の情報が入る
float[][] backRectInformations;//一手戻るボタンの座標の情報が入る
int proPiece[];//なる前の駒の番号が入る
int popCheck;

public void initPopUp() {
  anyRectInformations = new float[2][4];
  forcedRectInformations = new float[4];
  pawnRectInformations = new float[4][4];
  resignRectInformations = new float[2][4];
  backRectInformations = new float[2][4];
  popCheck = 0;//
  proPiece = new int[3];
}

public void anyPopUp() {//任意の成りのポップアップの処理。pop==1
  popCheck = 0;//1が入ると成る、2が　入ると成らないを表す
  viewAnyPopUp();//ポップアップを表示する
  fill(0xFFFFFF00, 150);
  for ( int n = 0; n < anyRectInformations.length; n++) {
    float x, y, s_x, s_y;
    x = anyRectInformations[n][0];
    y = anyRectInformations[n][1];
    s_x = anyRectInformations[n][2];
    s_y = anyRectInformations[n][3];
    if (mouseX >= x && mouseX<= x+s_x && mouseY >= y&& mouseY <= y+s_y) {
      popCheck = n+1;
      rect(x, y, s_x, s_y);
      break;
    }
  }
}

public void forcedPopUp() {//強制の成りのポップアップの処理
  viewForcedPopUp();
  fill(0xFFFFFF00, 150);
  float x, y, s_x, s_y;
  x = forcedRectInformations[0];
  y = forcedRectInformations[1];
  s_x = forcedRectInformations[2];
  s_y = forcedRectInformations[3];
  if (mouseX >= x && mouseX<= x+s_x && mouseY >= y&& mouseY <= y+s_y) {
    popCheck = 1;
    rect(x, y, s_x, s_y);
  }
}

public void pawnPopUp() {//ポーンのプロモーション(成り)のポップアップ
  viewPawnPopUp();
  fill(0xFFFFFF00, 150);
  for ( int n = 0; n < pawnRectInformations.length; n++) {
    float x, y, s_x, s_y;
    x = pawnRectInformations[n][0];
    y = pawnRectInformations[n][1];
    s_x = pawnRectInformations[n][2];
    s_y = pawnRectInformations[n][3];
    if (mouseX >= x && mouseX<= x+s_x && mouseY >= y&& mouseY <= y+s_y) {
      popCheck = n+1;
      rect(x, y, s_x, s_y);
      break;
    }
  }
}
public void resignPopUp() {//降参するときに出てくるポップアップ:pop = 4
  popCheck = 0;//1が入ると成る、2が入ると成らないを表す
  viewResignPopUp();//ポップアップを表示する
  fill(0xFFFFFF00, 150);
  for ( int n = 0; n < anyRectInformations.length; n++) {
    float x, y, s_x, s_y;
    x = resignRectInformations[n][0];
    y = resignRectInformations[n][1];
    s_x = resignRectInformations[n][2];
    s_y = resignRectInformations[n][3];
    if (mouseX >= x && mouseX<= x+s_x && mouseY >= y&& mouseY <= y+s_y) {
      popCheck = n+1;
      rect(x, y, s_x, s_y);
      break;
    }
  }
}
public void backPopUp() {//一手戻るためのポップアップ
  popCheck = 0;//1が入ると成る、2が入ると成らないを表す
  viewBackPopUp();//ポップアップを表示する
  fill(0xFFFFFF00, 150);
  for ( int n = 0; n < anyRectInformations.length; n++) {
    float x, y, s_x, s_y;
    x = backRectInformations[n][0];
    y = backRectInformations[n][1];
    s_x = backRectInformations[n][2];
    s_y = backRectInformations[n][3];
    if (mouseX >= x && mouseX<= x+s_x && mouseY >= y&& mouseY <= y+s_y) {
      popCheck = n+1;
      rect(x, y, s_x, s_y);
      break;
    }
  }
}
public void viewAnyPopUp() {
  fill(0xFFF6E5CC);
  float rect_x, rect_y, rect_x_size, rect_y_size;
  rect_x = stage_x + box_size;
  rect_y = stage_y + box_size;
  rect_x_size = stage_size/1.5f + box_size;
  rect_y_size = rect_x_size * 0.8f;

  rect(rect_x, rect_y, rect_x_size, rect_y_size);
  int t_s;
  t_s = 50;
  textSize(t_s);
  fill(0);
  text("成りますか？", (rect_x_size/2) + rect_x - t_s * 3, rect_y + 80);
  t_s = 30;
  textSize(t_s);
  int rect_color[] = {125, 125, 125};
  int text_color[] = {0, 0, 0};
  textRect(rect_x + 100, (rect_y+rect_y_size)/2 + 130, "成る", t_s, rect_color, text_color);
  anyRectInformations[0][0] = rect_x + 100+5 ;//x座標
  anyRectInformations[0][1] = (rect_y+rect_y_size)/2 + 130 + 5;//y座標
  anyRectInformations[0][2] = 2*t_s + 10;//横幅
  anyRectInformations[0][3] = t_s + 10;//縦幅

  textRect(rect_x + 250, (rect_y+rect_y_size)/2 + 130, "成らない", t_s, rect_color, text_color);
  anyRectInformations[1][0] = rect_x + 250+5 ;//x座標
  anyRectInformations[1][1] = (rect_y+rect_y_size)/2 + 130 + 5;//y座標
  anyRectInformations[1][2] = 4*t_s + 10;//横幅
  anyRectInformations[1][3] = t_s + 10;//縦幅
}

public void viewForcedPopUp() {
  fill(0xFFF6E5CC);
  float rect_x, rect_y, rect_x_size, rect_y_size;
  rect_x = stage_x + box_size;
  rect_y = stage_y + box_size;
  rect_x_size = stage_size/1.5f + box_size;
  rect_y_size = rect_x_size * 0.8f;

  rect(rect_x, rect_y, rect_x_size, rect_y_size);
  int t_s;
  t_s = 50;
  textSize(t_s);
  fill(0);
  text("成りました", (rect_x_size/2) + rect_x - t_s * 2.5f, rect_y + 80);
  t_s = 30;
  textSize(t_s);
  int rect_color[] = {125, 125, 125};
  int text_color[] = {0, 0, 0};
  textRect(rect_x + (rect_x_size)/2 - 40, (rect_y+rect_y_size)/2 + 130, "OK", t_s, rect_color, text_color);
  forcedRectInformations[0] =rect_x + (rect_x_size)/2 - 40+5 ;//x座標
  forcedRectInformations[1] = (rect_y+rect_y_size)/2 + 130 + 5;//y座標
  forcedRectInformations[2] = 2*t_s + 10;//横幅
  forcedRectInformations[3] = t_s + 10;//縦幅
}

public void viewPawnPopUp() {
  fill(0xFFF6E5CC);
  float rect_x, rect_y, rect_x_size, rect_y_size;
  rect_x = stage_x + box_size;
  rect_y = stage_y + box_size;
  rect_x_size = stage_size/1.5f + box_size;
  rect_y_size = rect_x_size * 0.8f;

  rect(rect_x, rect_y, rect_x_size, rect_y_size);
  int t_s;
  t_s = 50;
  textSize(t_s);
  fill(0);
  text("どれになりますか？", (rect_x_size/2) + rect_x - t_s * 4.5f, rect_y + 80);
  t_s = 30;
  textSize(t_s);
  int rect_color[] = {159, 159, 152};
  int text_color[] = {0, 0, 0};
  textRect(rect_x + 50, (rect_y+rect_y_size)/2 + 130, "クイーン", t_s, rect_color, text_color);
  pawnRectInformations[0][0] = rect_x + 50+5 ;//x座標
  pawnRectInformations[0][1] = (rect_y+rect_y_size)/2 + 130 + 5;//y座標
  pawnRectInformations[0][2] = 4*t_s + 10;//横幅
  pawnRectInformations[0][3] = t_s + 10;//縦幅

  textRect(rect_x + 50, (rect_y+rect_y_size)/2 + 180, "ビショップ", t_s, rect_color, text_color);
  pawnRectInformations[1][0] = rect_x + 50+5 ;//x座標
  pawnRectInformations[1][1] = (rect_y+rect_y_size)/2 + 180 + 5;//y座標
  pawnRectInformations[1][2] = 5*t_s + 10;//横幅
  pawnRectInformations[1][3] = t_s + 10;//縦幅

  textRect(rect_x + 300, (rect_y+rect_y_size)/2 + 130, "ルーク", t_s, rect_color, text_color);
  pawnRectInformations[2][0] = rect_x + 300+5 ;//x座標
  pawnRectInformations[2][1] = (rect_y+rect_y_size)/2 + 130 + 5;//y座標
  pawnRectInformations[2][2] = 3*t_s + 10;//横幅
  pawnRectInformations[2][3] = t_s + 10;//縦幅

  textRect(rect_x + 300, (rect_y+rect_y_size)/2 + 180, "ナイト", t_s, rect_color, text_color);
  pawnRectInformations[3][0] = rect_x + 300+5 ;//x座標
  pawnRectInformations[3][1] = (rect_y+rect_y_size)/2 + 180 + 5;//y座標
  pawnRectInformations[3][2] = 3*t_s + 10;//横幅
  pawnRectInformations[3][3] = t_s + 10;//縦幅
}
public void viewResignPopUp() {
  fill(0xFFF6E5CC);
  float rect_x, rect_y, rect_x_size, rect_y_size;
  rect_x = stage_x + box_size;
  rect_y = stage_y + box_size;
  rect_x_size = stage_size/1.5f + box_size;
  rect_y_size = rect_x_size * 0.8f;

  rect(rect_x, rect_y, rect_x_size, rect_y_size);
  int t_s;
  t_s = 50;
  textSize(t_s);
  fill(0);
  text("降参しますか？", (rect_x_size/2) + rect_x - t_s * 3.5f, rect_y + 80);
  t_s = 30;
  textSize(t_s);
  int rect_color[] = {125, 125, 125};
  int text_color[] = {0, 0, 0};
  textRect(rect_x + 100, (rect_y+rect_y_size)/2 + 130, "降参する", t_s, rect_color, text_color);
  resignRectInformations[0][0] = rect_x + 100+5 ;//x座標
  resignRectInformations[0][1] = (rect_y+rect_y_size)/2 + 130 + 5;//y座標
  resignRectInformations[0][2] = 4*t_s + 10;//横幅
  resignRectInformations[0][3] = t_s + 10;//縦幅

  textRect(rect_x + 250, (rect_y+rect_y_size)/2 + 130, "降参しない", t_s, rect_color, text_color);
  resignRectInformations[1][0] = rect_x + 250+5 ;//x座標
  resignRectInformations[1][1] = (rect_y+rect_y_size)/2 + 130 + 5;//y座標
  resignRectInformations[1][2] = 5*t_s + 10;//横幅
  resignRectInformations[1][3] = t_s + 10;//縦幅
}
public void viewBackPopUp() {
  fill(0xFFF6E5CC);
  float rect_x, rect_y, rect_x_size, rect_y_size;
  rect_x = stage_x + box_size;
  rect_y = stage_y + box_size;
  rect_x_size = stage_size/1.5f + box_size;
  rect_y_size = rect_x_size * 0.8f;

  rect(rect_x, rect_y, rect_x_size, rect_y_size);
  int t_s;
  t_s = 50;
  textSize(t_s);
  fill(0);
  text("一手戻りますか？", (rect_x_size/2) + rect_x - t_s * 3.5f, rect_y + 80);
  t_s = 30;
  textSize(t_s);
  int rect_color[] = {125, 125, 125};
  int text_color[] = {0, 0, 0};
  textRect(rect_x + 100, (rect_y+rect_y_size)/2 + 130, "一手戻る", t_s, rect_color, text_color);
  backRectInformations[0][0] = rect_x + 100+5 ;//x座標
  backRectInformations[0][1] = (rect_y+rect_y_size)/2 + 130 + 5;//y座標
  backRectInformations[0][2] = 4*t_s + 10;//横幅
  backRectInformations[0][3] = t_s + 10;//縦幅

  textRect(rect_x + 250, (rect_y+rect_y_size)/2 + 130, "戻らない", t_s, rect_color, text_color);
  backRectInformations[1][0] = rect_x + 250+5 ;//x座標
  backRectInformations[1][1] = (rect_y+rect_y_size)/2 + 130 + 5;//y座標
  backRectInformations[1][2] = 4*t_s + 10;//横幅
  backRectInformations[1][3] = t_s + 10;//縦幅
}
public int popCheck(int piece_num, int y, int x, int ex_y ) {//成れるかどうかのチェックを行う
  int pop;
  pop = 0;//1が任意、2が強制、3がポーン。1つがtrueのときは他をfalseにする
  int[] soeji;
  soeji = bunnkai(stage_piece_num[y][x]);
  int soeji1, soeji2, soeji3;
  soeji1 = soeji[0];
  soeji2 = soeji[1];
  soeji3 = soeji[2];
  proPiece[0] = piece_num;//動く先の番号が入る
  proPiece[1] = y;
  proPiece[2] = x;

  /*入れ子構造になりまくって見にくくなったのでelseを使わずに分けました*/
  if (soeji1 == 1) {//下側のとき
    if (soeji2 == 0 && rules[2]) {//将棋のとき

      if (soeji3 == 4 || soeji3 == 6 || soeji3 == 7) {//銀、角、飛車のどれかだったらここ
        if ( y <= 2 || ex_y <= 2) {//うえ3列から上だったら
          pop = 1;
        }
      } else if (soeji3 == 3) {//桂馬だったら
        if (y <= 1) {//強制の方
          pop = 2;
        } else if ( y == 2) {//任意の方
          pop = 1;
        }
      } else if (soeji3 == 1 || soeji3 == 2) {//香車と歩兵
        if (y == 0) {//強制の方
          pop = 2;
        } else if (y <= 2) {//任意の方
          pop = 1;
        }
      }
    } else if (soeji3 == 1 && y == 0 && rules[3]) {//チェスのとき(ポーンのみ)

      pop = 3;
    }
  }

  if (soeji1 == 2) {//上側のとき
    if (soeji2 == 0 && rules[2]) {//将棋のとき

      if (soeji3 == 4 || soeji3 == 6 || soeji3 == 7) {//銀、角、飛車のどれかだったらここ
        if ( y >= 6 || ex_y >= 6) {//下3列から下だったら,敵陣地から出たときにも成ることができる
          pop = 1;
        }
      } else if (soeji3 == 3) {//桂馬だったら
        if (y >= 7) {//強制の方
          pop = 2;
        } else if ( y == 6) {//任意の方
          pop = 1;
        }
      } else if (soeji3 == 1 || soeji3 == 2) {//香車と歩兵
        if (y == 8) {//強制の方
          pop = 2;
        } else if (y >= 6) {//任意の方
          pop = 1;
        }
      }
    } else if (soeji3 == 1 && y == 8 && rules[3]) {//チェスのとき(ポーンのみ)

      pop = 3;
    }
  }
  return pop;
}
public void originalSet() {//オリジナルモードのセットアップ
  rules[0] = true;//将棋の持ち駒
  rules[1] = false;//チェスの持ち駒
  rules[2] = true;//将棋の成り
  rules[3] = true;//チェスの成り
  rules[4] = false;//将棋のキャスリング
  rules[5] = true;//チェスのキャスリング(実装しなかったら消す)
}

public void balanceSet() {//バランスモードのセットアップ
  rules[0] = true;//将棋の持ち駒
  rules[1] = true;//チェスの持ち駒
  rules[2] = true;//将棋の成り
  rules[3] = false;//チェスの成り
  rules[4] = true;//将棋のキャスリング
  rules[5] = true;//チェスのキャスリング
}
public void customSet() {//カスタムモードのセットアップ
  switch(option1_num) {
  case 0:
    rules[0] = false;
    rules[1] = false;
    break;

  case 1:
    rules[0] = true;
    rules[1] = true;
    break;

  case 2:
    rules[0] = true;
    rules[1] = false;
    break;

  case 3:
    rules[0] = false;
    rules[1] = true;
    break;
  }
  switch(option2_num) {
  case 0:
    rules[2] = false;
    rules[3] = false;
    break;

  case 1:
    rules[2] = true;
    rules[3] = true;
    break;

  case 2:
    rules[2] = true;
    rules[3] = false;
    break;

  case 3:
    rules[2] = false;
    rules[3] = true;
    break;
  }
  switch(option3_num) {
  case 0:
    rules[4] = false;
    rules[5] = false;
    break;

  case 1:
    rules[4] = true;
    rules[5] = true;
    break;

  case 2:
    rules[4] = true;
    rules[5] = false;
    break;

  case 3:
    rules[4] = false;
    rules[5] = true;
    break;
  }
}
Minim minim;//音を扱うために必要な変数
AudioPlayer move_piece_sound;
public void initSound() {
  minim = new Minim(this);
  move_piece_sound = minim.loadFile("data/sound/指す.mp3");//サウンドファイルのインポーロ
  move_piece_sound.setGain(6);
}
int time;//タイマーを動かすときに使われる変数
boolean time_han;
public void initTimer() {
  time = 0;
  time_han = false;//タイマーを動かない状態にする
}

public void startTimer() {//タイマーをスタートする関数
  time_han = true;
}
public void stopTimer() {//タイマーを止める関数
  time_han = false;
}
public void resetTimer() {//タイマーの数値をリセットする関数
  time = 0;
}
public void viewTimer(float x, float y, int time) {
  String hour, minute, second;//分と秒が文字列として入る
  int hourValue, minuteValue, secondValue;
  hourValue = (time/FPS) / 3600;//時間の値がここに入る
  minuteValue = (time/FPS)/60 % 60;//分の値がここに入る
  secondValue = (time/FPS)%60;//秒の値がここに入る

  hour = str(hourValue);
  minute = str(minuteValue);
  second = str(secondValue);
  if (minute.length() == 1) {//もし分が1桁だったらここの処理が行われる
    minute = "0" + minute;//数字の左に0をつける
  }
  if (second.length() == 1) {//もし秒が1桁だったらここの処理が行われる
    second = "0" + second;
  }
  text(hour+":"+minute + ":" + second, x, y);
}

public void viewRightTimer(float x, float y, int time, int t_s) {//座標を左上ではなく右上基準で描画するタイマー
  String hour, minute, second;//分と秒が文字列として入る
  String timeMoji;
  int hourValue, minuteValue, secondValue;
  hourValue = (time/FPS) / 3600;//時間の値がここに入る
  minuteValue = (time/FPS)/60 % 60;//分の値がここに入る
  secondValue = (time/FPS)%60;//秒の値がここに入る

  hour = str(hourValue);
  minute = str(minuteValue);
  second = str(secondValue);
  if (minute.length() == 1) {//もし分が1桁だったらここの処理が行われる
    minute = "0" + minute;//数字の左に0をつける
  }
  if (second.length() == 1) {//もし秒が1桁だったらここの処理が行われる
    second = "0" + second;
  }
  timeMoji = hour+":"+minute + ":" + second;
  text(timeMoji, x-(timeMoji.length()/2 * t_s), y);
}

/*将棋とチェスと陣営を分けるために将棋は2桁で[0n],チェスは[1n]と表し陣営は下が[1nm]、上が[2nm]とあらわす
 例.下の歩→001,上のN→113*/
String[][] stage_piece;//使わないかも
int[][] stage_piece_num;//[y座標][x座標]
boolean canPuts[][] = new boolean[9][9];
String stage_moji[] = new String[9];
public void initView() {//盤面や表示に関する初期化
  stage_x = (width-consoleSize)/2 - stage_size/2;
  stage_y = height/2 - stage_size/2;
  s_size= new float[9][9];
  box_size=stage_size/9;//マス目の大きさ
  stage_piece = new String[9][9];
  stage_piece_num = new int[9][9];
  for (int n = 0; n < stage_piece.length; n++) {
    for (int j = 0; j < stage_piece[n].length; j++) {
      stage_piece[n][j] = null;//配列の中すべてに[null]を入れる
      stage_piece_num[n][j] = 0;//配列の中すべてに[0]を入れる
    }
  }

  stage_moji[0] ="a";
  stage_moji[1] ="b";
  stage_moji[2] ="c";
  stage_moji[3] ="d";
  stage_moji[4] ="e";
  stage_moji[5] ="f";
  stage_moji[6] ="g";
  stage_moji[7] ="h";
  stage_moji[8] ="i";
  initChessPiece();//(上側)チェスの盤面の初期化
  initSyogiPiece();//(下側)将棋の盤面の初期化
}

public void initChessPiece() {
  for (int n = 0; n < 8; n++) {
    stage_piece_num[1][n] = 211;//211はポーン(P)
  }
  stage_piece_num[0][0] = 212;//212はルーク(R)
  stage_piece_num[0][7] = 212;
  stage_piece_num[0][1] = 213;//213はナイト(N)
  stage_piece_num[0][6] = 213;
  stage_piece_num[0][2] = 214;//214はビショップ(B)
  stage_piece_num[0][5] = 214;
  stage_piece_num[0][3] = 215;//215はクイーン(Q)
  stage_piece_num[0][4] = 210;//210はキング(K)
}

public void initSyogiPiece() {
  for (int n = 0; n < 9; n++) {
    stage_piece_num[6][n] = 101;//101は歩
  }
  stage_piece_num[8][0] = 102;//102は香車
  stage_piece_num[8][8] = 102;
  stage_piece_num[8][1] = 103;//103は桂馬
  stage_piece_num[8][7] = 103;
  stage_piece_num[8][2] = 104;//104は銀将
  stage_piece_num[8][6] = 104;
  stage_piece_num[8][3] = 105;//105は金将
  stage_piece_num[8][5] = 105;
  stage_piece_num[8][4] = 100;//100は王
  stage_piece_num[7][1] = 106;//106は角行
  stage_piece_num[7][7] = 107;//107は飛車
}


public void view() {//チェス将棋盤と駒の画像を書く処理

  String turnText;
  if (turn_num == 1) {
    turnText = "下側のターンです";
    textSize(24);
    text("こちら側のターンです", width-consoleSize - 240, height - 50);
  } else {
    turnText = "上側のターンです";
    textSize(24);
    text("こちら側のターンです", 0, 90);
  }
  fill(255);
  textSize(20);
  text(turnText, (width-consoleSize), 100);

  for (int n = 0; n<s_size.length; n++) {//盤面の出力
    for (int j = 0; j<s_size[n].length; j++) {
      if ((n+j)%2==0) {
        fill(42, 106, 204);
      } else {
        fill(0xFFD59533);
      }
      rect(stage_x + box_size*n, stage_y + box_size*j, box_size, box_size);//盤面
    }
  }
  fill(0);
  textSize(19);
  for (int n = 0; n< 9; n++) {//盤の横の数字
    text(9-n, stage_x + box_size*(-0.4f), stage_y+box_size*(n+0.6f));
    text(stage_moji[n], stage_x+box_size*(n+0.45f), stage_y + box_size*(-0.2f));
  }



  /*駒を描画する処理*/
  fill(0);
  for (int n = 0; n < stage_piece_num.length; n++) {
    for (int j = 0; j < stage_piece_num[n].length; j++) {
      if (stage_piece_num[n][j] != 0) {
        int[] soeji;
        soeji = bunnkai(stage_piece_num[n][j]);//数字が1桁ごとに抽出される(4桁のときは3,4桁はまとまる)
        if (soeji[1] == 0) {//将棋のときの処理
          if (soeji[0] == 1) {//下側陣営
            image(syogi_images[soeji[2]], stage_x + box_size*j + 3, stage_y + box_size*n + 4);
          } else {//上側陣営
            image(reverse_images[soeji[2]], stage_x + box_size*j + 3, stage_y + box_size*n + 4);
          }
        } else {//チェスのときの処理
          if (soeji[0] == 1) {//下側陣営
            image(reverse_chess[soeji[2]], stage_x + box_size*j + 3, stage_y + box_size*n + 4);
          } else {//上側陣営
            image(chess_images[soeji[2]], stage_x + box_size*j + 3, stage_y + box_size*n + 4);
          }
        }
      }
    }
  }
}

public void viewChoose(int x, int y) {//多分ここはいらない
  int soeji[];//数字をして添え字にする
  soeji = bunnkai(stage_piece_num[y][x]);

  fill(0, 255, 0, 64);
  rect(stage_x + box_size*x, stage_y + box_size*y, box_size, box_size);//選択した駒のマスに色を付ける
}

//void stageView() {//チェス将棋盤を書く処理
//}

public void moveView(int y, int x) {
  int soeji[];
  soeji = bunnkai(stage_piece_num[y][x]);
  int viewCanMove[][];//ここにはどのマスに動けるかが入る
  int remit;
  remit = 32;
  fill(0, 255, 0, 64);
  rect(stage_x + box_size*x, stage_y + box_size*y, box_size, box_size);
  if ( soeji[0] == 1) {//下側陣営のとき
    viewCanMove = downCanMove[y][x];
  } else {
    viewCanMove = upCanMove[y][x];
  }
  int c = 0;
  fill(0xFFFF0000, 80);

  while (viewCanMove[c][0] != -1 ) {
    int v_y, v_x;
    v_y = viewCanMove[c][0];
    v_x = viewCanMove[c][1];
    rect(stage_x + box_size*v_x, stage_y + box_size*v_y, box_size, box_size);

    c += 1;
    if ( c >= remit) {
      break;
    }
  }
}

public boolean canPutCheck(int y, int x) {//マウスが動けるマスにあったら黄色になるようにする
  boolean canMove;//
  int soeji[];
  soeji = bunnkai(stage_piece_num[y][x]);
  int viewCanMove[][];//ここにはどのマスに動けるかが入る
  int remit;
  remit = 32;
  if ( soeji[0] == 1) {//下側陣営のとき
    viewCanMove = downCanMove[y][x];
  } else {
    viewCanMove = upCanMove[y][x];
  }

  /*ここからは駒を動けるようにする処理を書く*/
  canMove = false;
  if ((mouseX>= stage_x && mouseX < stage_x+stage_size) &&(mouseY >= stage_y && mouseY < stage_y + stage_size)) {//マウスが盤上にあったら処理をする
    int mouse_x = (((mouseX-6) - PApplet.parseInt(stage_x))/ (PApplet.parseInt(stage_size)/9));//盤上の座標
    int mouse_y = (((mouseY-6) - PApplet.parseInt(stage_y))/ (PApplet.parseInt(stage_size)/9));
    int d = 0;//カウント用の変数
    while (viewCanMove[d][0] != -1) {
      if (viewCanMove[d][0] == mouse_y && viewCanMove[d][1] == mouse_x) {
        fill(0, 255, 0, 80);//駒がある位置を黄色にする
        rect(stage_x + box_size*mouse_x, stage_y + box_size*mouse_y, box_size, box_size);
        canMove = true;
        break;
      }


      d += 1;
      if ( d >= remit) {
        break;
      }
    }
  }
  return canMove;
}

public void haveMoveView(float haveX, float haveY, int num, int option) {
  float checkX, checkY;
  switch(num) {
  case 1://下側の左
    checkX = stage_x + box_size*10.5f;//下側の左
    checkY = stage_y + box_size*6;
    break;

  case 2://下側の右
    checkX = stage_x + box_size*12;//下側の右
    checkY = stage_y + box_size*6;
    break;

  case 3://上側の左
    checkX = stage_x + box_size*(-4);//上側の左
    checkY = stage_y + 40;
    break;

  case 4://上側の右
    checkX = stage_x + box_size*(-2.5f);//上側の右
    checkY = stage_y + 40;
    break;

  default://ここを通ることは絶対にない
    checkX =0;
    checkY = 0;
    break;
  }
  if (num == 1 || num == 3) {//上でも下で左側の時の処理
    for (int n = 0; n < 4; n++) {
      int j = 3 - n;
      if (haveY >= checkY + j*40) {
        fill(0, 255, 0, 64);
        rect(checkX, checkY + j*40, 40, 40);

        break;
      }
    }
  } else {//右側の時の処理
    for (int n = 0; n < 3; n++) {
      int j = 2 - n;
      if (haveY >= checkY + j*40) {
        fill(0, 255, 0, 64);
        rect(checkX, checkY + j*40, 40, 40);

        break;
      }
    }
  }

  boolean haveCanPut[][] = new boolean[9][9];
  if (num <= 2) {//下側陣営
    if (option == 0) {//歩兵だったら
      haveCanPut = downHuhyoCanPut;
    } else if (option == 1) {//香車だったら
      haveCanPut = downKyosyaCanPut;
    } else if (option == 2) {//桂馬だったら
      haveCanPut = downKeimaCanPut;
    } else {//それ以外の駒だったら
      haveCanPut = normalCanPut;
    }
  } else {//上側陣営
    if (option == 0) {//歩兵だったら
      haveCanPut = upHuhyoCanPut;
    } else if (option == 1) {//香車だったら
      haveCanPut = upKyosyaCanPut;
    } else if (option == 2) {//桂馬だったら
      haveCanPut = upKeimaCanPut;
    } else {//それ以外の駒だったら
      haveCanPut = normalCanPut;
    }
  }
  canPuts = haveCanPut;//グローバル変数に保存
  fill(255, 0, 0, 80);//赤色に塗る
  for (int n = 0; n < haveCanPut.length; n++) {
    for (int j = 0; j < haveCanPut.length; j++) {
      if (haveCanPut[n][j]) {
        rect(stage_x + box_size*j, stage_y + box_size*n, box_size, box_size);//マウスがある位置を塗る
      }
    }
  }
}
public void haveChessMoveView(float haveX, float haveY, int num, int option) {
  float checkX, checkY;
  switch(num) {
  case 5://下側の左
    checkX = stage_x + box_size*10.5f;//下側の左
    checkY = stage_y + box_size*6 - 180;
    break;

  case 6://下側の右
    checkX = stage_x + box_size*12;//下側の右
    checkY = stage_y + box_size*6 - 180;
    break;

  case 7://上側の左
    checkX = stage_x + box_size*(-4);//上側の左
    checkY = stage_y + 260;
    break;

  case 8://上側の右
    checkX = stage_x + box_size*(-2.5f);//上側の右
    checkY = stage_y + 260;
    break;

  default://ここを通ることは絶対にない
    checkX =0;
    checkY = 0;
    break;
  }
  if (num == 5 || num == 7) {//上でも下で左側の時の処理
    for (int n = 0; n < 3; n++) {
      int j = 2 - n;
      if (haveY >= checkY + j*40) {
        fill(0, 255, 0, 64);
        rect(checkX, checkY + j*40, 40, 40);

        break;
      }
    }
  } else {//右側の時の処理
    for (int n = 0; n < 2; n++) {
      int j = 1 - n;
      if (haveY >= checkY + j*40) {
        fill(0, 255, 0, 64);
        rect(checkX, checkY + j*40, 40, 40);

        break;
      }
    }
  }

  boolean haveCanPut[][] = new boolean[9][9];
  if (num <= 6) {//下側陣営
    if (option == 0) {//ポーンだったら
      haveCanPut = downKyosyaCanPut;
    } else {//それ以外の駒だったら
      haveCanPut = normalCanPut;
    }
  } else {//上側陣営
    if (option == 0) {//歩兵だったら
      haveCanPut = upKyosyaCanPut;
    } else {//それ以外の駒だったら
      haveCanPut = normalCanPut;
    }
  }
  canPuts = haveCanPut;//グローバル変数に保存
  fill(255, 0, 0, 80);//赤色に塗る
  for (int n = 0; n < haveCanPut.length; n++) {
    for (int j = 0; j < haveCanPut.length; j++) {
      if (haveCanPut[n][j]) {
        rect(stage_x + box_size*j, stage_y + box_size*n, box_size, box_size);//マウスがある位置を塗る
      }
    }
  }
}

public void viewCheck() {
  fill(255);
  textSize(30);
  text("王手中です", width-consoleSize + 20, height/2+50);
}


  public void settings() { size(1420, 800); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Chess_vs_Shogi" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
